rm -R -f build
mkdir build
cd build
CC="cc -Wno-error=strict-prototypes" cmake \
-DCMAKE_OSX_ARCHITECTURES=arm64 \
-DWITH_SFTP=ON \
-DWITH_SERVER=ON \
-DWITH_GEX=ON \
-DWITH_INSECURE_NONE=ON \
-DWITH_PCAP=ON \
-DWITH_BLOWFISH_CIPHER=ON \
-DWITH_DSA=ON \
-DWITH_EXAMPLES=OFF \
-DWITH_INTERNAL_DOC=ON \
-DWITH_BENCHMARKS=OFF \
-DWITH_FINAL=OFF \
-DGLOBAL_CLIENT_CONFIG=ON \
-DGLOBAL_BIND_CONFIG=ON \
-DUNIT_TESTING=OFF \
-DCLIENT_TESTING=OFF \
-DSERVER_TESTING=OFF \
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
make
