.TH "/home/mock/cryptopp-master/3way.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/3way.h \- Classes for the 3-Way block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBThreeWay_Info\fP"
.br
.RI "\fBThreeWay\fP block cipher information\&. "
.ti -1c
.RI "class \fBThreeWay\fP"
.br
.RI "\fBThreeWay\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBThreeWay::Encryption\fP \fBThreeWayEncryption\fP"
.br
.ti -1c
.RI "typedef \fBThreeWay::Decryption\fP \fBThreeWayDecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the 3-Way block cipher\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
