.TH "/home/mock/cryptopp-master/adler32.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/adler32.h \- Class file for ADLER-32 checksum calculations\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdler32\fP"
.br
.RI "ADLER-32 checksum calculations\&. "
.in -1c
.SH "Detailed Description"
.PP
Class file for ADLER-32 checksum calculations\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
