.TH "/home/mock/cryptopp-master/adv_simd.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/adv_simd.h \- Template for AdvancedProcessBlocks and SIMD processing\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br
\fR#include 'stdcpp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BT_XorInput=\fBBlockTransformation::BT_XorInput\fP)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BT_AllowParallel=\fBBlockTransformation::BT_AllowParallel\fP)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BT_InBlockIsCounter=\fBBlockTransformation::BT_InBlockIsCounter\fP)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BT_ReverseDirection=\fBBlockTransformation::BT_ReverseDirection\fP)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BT_DontIncrementInOutPointers=\fBBlockTransformation::BT_DontIncrementInOutPointers\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP
Template for AdvancedProcessBlocks and SIMD processing\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
