.TH "/home/mock/cryptopp-master/aes.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/aes.h \- Class file for the AES cipher (\fBRijndael\fP)

.SH SYNOPSIS
.br
.PP
\fR#include 'rijndael\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRijndaelEncryption\fP \fBAESEncryption\fP"
.br
.ti -1c
.RI "typedef \fBRijndaelDecryption\fP \fBAESDecryption\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBRijndael\fP, AES)"
.br
.RI "AES block cipher (\fBRijndael\fP) "
.in -1c
.SH "Detailed Description"
.PP
Class file for the AES cipher (\fBRijndael\fP)

AES is a typdef for \fBRijndael\fP classes\&. All key sizes are supported\&. The library only provides \fBRijndael\fP with 128-bit blocks, and not 192-bit or 256-bit blocks
.PP
\fBSince\fP
.RS 4
\fBRijndael\fP since Crypto++ 3\&.1, Intel AES-NI since Crypto++ 5\&.6\&.1, ARMv8 AES since Crypto++ 6\&.0, Power8 AES since Crypto++ 6\&.0
.RE
.PP

.SH "Function Documentation"
.PP
.SS "DOCUMENTED_TYPEDEF (\fBRijndael\fP , AES )"

.PP
AES block cipher (\fBRijndael\fP) AES is a typdef for \fBRijndael\fP classes\&. All key sizes are supported\&. The library only provides \fBRijndael\fP with 128-bit blocks, and not 192-bit or 256-bit blocks
.PP
\fBSee also\fP
.RS 4
\fRAES\fP winner, announced on 10/2/2000
.RE
.PP
\fBSince\fP
.RS 4
\fBRijndael\fP since Crypto++ 3\&.1, Intel AES-NI since Crypto++ 5\&.6\&.1, ARMv8 AES since Crypto++ 6\&.0, Power8 AES since Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
