.TH "/home/mock/cryptopp-master/arc4.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/arc4.h \- Classes for ARC4 cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'strciphr\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'smartptr\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWeak1::ARC4_Base\fP"
.br
.RI "ARC4 base class\&. "
.ti -1c
.RI "class \fBWeak1::MARC4_Base\fP"
.br
.RI "MARC4 base class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBWeak1::DOCUMENTED_TYPEDEF\fP (\fBSymmetricCipherFinal\fP< \fBARC4_Base\fP >, ARC4)"
.br
.RI "Alleged RC4\&. "
.ti -1c
.RI "\fBWeak1::DOCUMENTED_TYPEDEF\fP (\fBSymmetricCipherFinal\fP< \fBMARC4_Base\fP >, MARC4)"
.br
.RI "Modified Alleged RC4\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for ARC4 cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.1
.RE
.PP

.SH "Function Documentation"
.PP
.SS "Weak1::DOCUMENTED_TYPEDEF (\fBSymmetricCipherFinal\fP< \fBARC4_Base\fP > , ARC4 )"

.PP
Alleged RC4\&.
.PP
\fBSee also\fP
.RS 4
\fRAlleged RC4\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.1
.RE
.PP

.SS "Weak1::DOCUMENTED_TYPEDEF (\fBSymmetricCipherFinal\fP< \fBMARC4_Base\fP > , MARC4 )"

.PP
Modified Alleged RC4\&.
.PP
\fBSee also\fP
.RS 4
\fRAlleged RC4\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.1
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
