.TH "/home/mock/cryptopp-master/aria.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/aria.h \- Classes for the \fBARIA\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBARIA_Info\fP"
.br
.RI "\fBARIA\fP block cipher information\&. "
.ti -1c
.RI "class \fBARIA\fP"
.br
.RI "\fBARIA\fP block cipher\&. "
.ti -1c
.RI "class \fBARIA::Base\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBARIA::Encryption\fP \fBARIAEncryption\fP"
.br
.ti -1c
.RI "typedef \fBARIA::Decryption\fP \fBARIADecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBARIA\fP block cipher\&.

The Crypto++ \fBARIA\fP implementation is based on the 32-bit implementation by Aaram Yun from the National Security Research Institute, KOREA\&. Aaram Yun's implementation is based on the 8-bit implementation by Jin Hong\&. The source files are available in ARIA\&.zip from the Korea Internet & Security Agency website\&.
.PP
\fBSee also\fP
.RS 4
\fRRFC 5794, A Description of the ARIA Encryption Algorithm\fP, \fRKorea Internet & Security Agency homepage\fP
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
