.TH "/home/mock/cryptopp-master/arm_simd.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/arm_simd.h \- Support functions for ARM and vector operations\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br

.SH "Detailed Description"
.PP
Support functions for ARM and vector operations\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
