.TH "ASNOptional< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASNOptional< T > \- Optional data encoder and decoder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <asn\&.h>\fP
.PP
Inherits \fBmember_ptr< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBERDecode\fP (\fBBERSequenceDecoder\fP &seqDecoder, \fBbyte\fP tag, \fBbyte\fP mask=~\fBCONSTRUCTED\fP)"
.br
.RI "BER decode optional data\&. "
.ti -1c
.RI "void \fBDEREncode\fP (\fBBufferedTransformation\fP &out)"
.br
.RI "DER encode optional data\&. "
.in -1c

Public Member Functions inherited from \fBmember_ptr< T >\fP
.in +1c
.ti -1c
.RI "\fBmember_ptr\fP (T *p=NULLPTR)"
.br
.ti -1c
.RI "const T & \fBoperator*\fP () const"
.br
.ti -1c
.RI "T & \fBoperator*\fP ()"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "const T * \fBget\fP () const"
.br
.ti -1c
.RI "T * \fBget\fP ()"
.br
.ti -1c
.RI "T * \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (T *p=NULLPTR)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBmember_ptr< T >\fP
.in +1c
.ti -1c
.RI "\fBmember_ptr\fP (const \fBmember_ptr\fP< T > &rhs)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBmember_ptr\fP< T > &rhs)"
.br
.in -1c

Protected Attributes inherited from \fBmember_ptr< T >\fP
.in +1c
.ti -1c
.RI "T * \fBm_p\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class ASNOptional< T >"Optional data encoder and decoder\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP class or type 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class T> void \fBASNOptional\fP< T >::BERDecode (\fBBERSequenceDecoder\fP & seqDecoder, \fBbyte\fP tag, \fBbyte\fP mask = \fR~\fBCONSTRUCTED\fP\fP)\fR [inline]\fP"

.PP
BER decode optional data\&. 
.PP
\fBParameters\fP
.RS 4
\fIseqDecoder\fP sequence with the optional ASN\&.1 data 
.br
\fItag\fP ASN\&.1 tag to match as optional data 
.br
\fImask\fP the mask to apply when matching the tag 
.RE
.PP
\fBSee also\fP
.RS 4
\fBASNTag\fP and \fBASNIdFlag\fP 
.RE
.PP

.SS "template<class T> void \fBASNOptional\fP< T >::DEREncode (\fBBufferedTransformation\fP & out)\fR [inline]\fP"

.PP
DER encode optional data\&. 
.PP
\fBParameters\fP
.RS 4
\fIout\fP \fBBufferedTransformation\fP object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
