.TH "AssignFromHelperClass< T, BASE >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AssignFromHelperClass< T, BASE >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignFromHelperClass\fP (T *pObject, const \fBNameValuePairs\fP &source)"
.br
.ti -1c
.RI "template<class R> \fBAssignFromHelperClass\fP & \fBoperator()\fP (const char *name, void(T::*pm)(const R &))"
.br
.ti -1c
.RI "template<class R, class S> \fBAssignFromHelperClass\fP & \fBoperator()\fP (const char *name1, const char *name2, void(T::*pm)(const R &, const S &))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
