.TH "/home/mock/cryptopp-master/basecode.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/basecode.h \- Base classes for working with encoders and decoders\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'filters\&.h'\fP
.br
\fR#include 'algparam\&.h'\fP
.br
\fR#include 'argnames\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseN_Encoder\fP"
.br
.RI "Encoder for bases that are a power of 2\&. "
.ti -1c
.RI "class \fBBaseN_Decoder\fP"
.br
.RI "Decoder for bases that are a power of 2\&. "
.ti -1c
.RI "class \fBGrouper\fP"
.br
.RI "\fBFilter\fP that breaks input stream into groups of fixed size\&. "
.in -1c
.SH "Detailed Description"
.PP
Base classes for working with encoders and decoders\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
