.TH "/home/mock/cryptopp-master/base32.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/base32.h \- Classes for \fBBase32Encoder\fP, \fBBase32Decoder\fP, \fBBase32HexEncoder\fP and \fBBase32HexDecoder\fP\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'basecode\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase32Encoder\fP"
.br
.RI "Base32 encodes data using DUDE encoding\&. "
.ti -1c
.RI "class \fBBase32Decoder\fP"
.br
.RI "Base32 decodes data using DUDE encoding\&. "
.ti -1c
.RI "class \fBBase32HexEncoder\fP"
.br
.RI "Base32 encodes data using extended hex\&. "
.ti -1c
.RI "class \fBBase32HexDecoder\fP"
.br
.RI "Base32 decodes data using extended hex\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBBase32Encoder\fP, \fBBase32Decoder\fP, \fBBase32HexEncoder\fP and \fBBase32HexDecoder\fP\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
