.TH "/home/mock/cryptopp-master/base64.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/base64.h \- Classes for the \fBBase64Encoder\fP, \fBBase64Decoder\fP, \fBBase64URLEncoder\fP and \fBBase64URLDecoder\fP\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'basecode\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase64Encoder\fP"
.br
.RI "Base64 encodes data using DUDE\&. "
.ti -1c
.RI "class \fBBase64Decoder\fP"
.br
.RI "Base64 decodes data using DUDE\&. "
.ti -1c
.RI "class \fBBase64URLEncoder\fP"
.br
.RI "Base64 encodes data using a web safe alphabet\&. "
.ti -1c
.RI "class \fBBase64URLDecoder\fP"
.br
.RI "Base64 decodes data using a web safe alphabet\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBBase64Encoder\fP, \fBBase64Decoder\fP, \fBBase64URLEncoder\fP and \fBBase64URLDecoder\fP\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
