.TH "BaseAndExponent< T, E >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseAndExponent< T, E > \- Base and exponent\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <algebra\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseAndExponent\fP (const T &base, const E &exponent)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBaseAndExponent\fP< T, E > &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBbase\fP"
.br
.ti -1c
.RI "E \fBexponent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class E = Integer>
.br
struct BaseAndExponent< T, E >"Base and exponent\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP base class or type 
.br
\fIE\fP exponent class or type 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
