.TH "/home/mock/cryptopp-master/blowfish.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/blowfish.h \- Classes for the \fBBlowfish\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBlowfish_Info\fP"
.br
.RI "\fBBlowfish\fP block cipher information\&. "
.ti -1c
.RI "class \fBBlowfish\fP"
.br
.RI "\fBBlowfish\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBBlowfish::Encryption\fP \fBBlowfishEncryption\fP"
.br
.ti -1c
.RI "typedef \fBBlowfish::Decryption\fP \fBBlowfishDecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBBlowfish\fP block cipher\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
