.TH "BlumBlumShub" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlumBlumShub \- \fBBlumBlumShub\fP with factorization of the modulus\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <blumshub\&.h>\fP
.PP
Inherits \fBPublicBlumBlumShub\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlumBlumShub\fP (const \fBInteger\fP &p, const \fBInteger\fP &q, const \fBInteger\fP &seed)"
.br
.RI "Construct a \fBBlumBlumShub\fP\&. "
.ti -1c
.RI "bool \fBIsRandomAccess\fP () const"
.br
.RI "Determines whether the cipher supports random access\&. "
.ti -1c
.RI "void \fBSeek\fP (\fBlword\fP index)"
.br
.RI "Seek to an absolute position\&. "
.in -1c

Public Member Functions inherited from \fBPublicBlumBlumShub\fP
.in +1c
.ti -1c
.RI "\fBPublicBlumBlumShub\fP (const \fBInteger\fP &n, const \fBInteger\fP &seed)"
.br
.RI "Construct a \fBPublicBlumBlumShub\fP\&. "
.ti -1c
.RI "unsigned int \fBGenerateBit\fP ()"
.br
.RI "Generate new random bit and return it\&. "
.ti -1c
.RI "\fBbyte\fP \fBGenerateByte\fP ()"
.br
.RI "Generate new random byte and return it\&. "
.ti -1c
.RI "void \fBGenerateBlock\fP (\fBbyte\fP *output, size_t size)"
.br
.RI "Generate random array of bytes\&. "
.ti -1c
.RI "void \fBProcessData\fP (\fBbyte\fP *outString, const \fBbyte\fP *inString, size_t length)"
.br
.RI "Encrypt or decrypt an array of bytes\&. "
.ti -1c
.RI "bool \fBIsSelfInverting\fP () const"
.br
.RI "Determines whether the cipher is self-inverting\&. "
.ti -1c
.RI "bool \fBIsForwardTransformation\fP () const"
.br
.RI "Determines if the cipher is being operated in its forward direction\&. "
.in -1c

Public Member Functions inherited from \fBRandomNumberGenerator\fP
.in +1c
.ti -1c
.RI "virtual void \fBIncorporateEntropy\fP (const \fBbyte\fP *input, size_t length)"
.br
.RI "Update RNG state with additional unpredictable values\&. "
.ti -1c
.RI "virtual bool \fBCanIncorporateEntropy\fP () const"
.br
.RI "Determines if a generator can accept additional entropy\&. "
.ti -1c
.RI "virtual \fBword32\fP \fBGenerateWord32\fP (\fBword32\fP min=0, \fBword32\fP max=0xffffffffUL)"
.br
.RI "Generate a random 32 bit word in the range min to max, inclusive\&. "
.ti -1c
.RI "virtual void \fBGenerateIntoBufferedTransformation\fP (\fBBufferedTransformation\fP &target, const std::string &channel, \fBlword\fP length)"
.br
.RI "Generate random bytes into a \fBBufferedTransformation\fP\&. "
.ti -1c
.RI "virtual void \fBDiscardBytes\fP (size_t n)"
.br
.RI "Generate and discard n bytes\&. "
.ti -1c
.RI "template<class IT> void \fBShuffle\fP (IT begin, IT end)"
.br
.RI "Randomly shuffle the specified array\&. "
.in -1c

Public Member Functions inherited from \fBAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (bool checkSelfTestStatus=true)"
.br
.RI "Interface for all crypto algorithms\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmName\fP () const"
.br
.RI "Provides the name of this algorithm\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmProvider\fP () const"
.br
.RI "Retrieve the provider of this algorithm\&. "
.in -1c

Public Member Functions inherited from \fBClonable\fP
.in +1c
.ti -1c
.RI "virtual \fBClonable\fP * \fBClone\fP () const"
.br
.RI "Copies this object\&. "
.in -1c

Public Member Functions inherited from \fBStreamTransformation\fP
.in +1c
.ti -1c
.RI "\fBStreamTransformation\fP & \fBRef\fP ()"
.br
.RI "Provides a reference to this object\&. "
.ti -1c
.RI "virtual unsigned int \fBMandatoryBlockSize\fP () const"
.br
.RI "Provides the mandatory block size of the cipher\&. "
.ti -1c
.RI "virtual unsigned int \fBOptimalBlockSize\fP () const"
.br
.RI "Provides the input block size most efficient for this cipher\&. "
.ti -1c
.RI "virtual unsigned int \fBGetOptimalBlockSizeUsed\fP () const"
.br
.RI "Provides the number of bytes used in the current block when processing at optimal block size\&. "
.ti -1c
.RI "virtual unsigned int \fBOptimalDataAlignment\fP () const"
.br
.RI "Provides input and output data alignment for optimal performance\&. "
.ti -1c
.RI "virtual size_t \fBProcessLastBlock\fP (\fBbyte\fP *outString, size_t outLength, const \fBbyte\fP *inString, size_t inLength)"
.br
.RI "Encrypt or decrypt the last block of data\&. "
.ti -1c
.RI "virtual unsigned int \fBMinLastBlockSize\fP () const"
.br
.RI "Provides the size of the last block\&. "
.ti -1c
.RI "virtual bool \fBIsLastBlockSpecial\fP () const"
.br
.RI "Determines if the last block receives special processing\&. "
.ti -1c
.RI "void \fBProcessString\fP (\fBbyte\fP *inoutString, size_t length)"
.br
.RI "Encrypt or decrypt a string of bytes\&. "
.ti -1c
.RI "void \fBProcessString\fP (\fBbyte\fP *outString, const \fBbyte\fP *inString, size_t length)"
.br
.RI "Encrypt or decrypt a string of bytes\&. "
.ti -1c
.RI "\fBbyte\fP \fBProcessByte\fP (\fBbyte\fP input)"
.br
.RI "Encrypt or decrypt a byte\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBInteger\fP \fBp\fP"
.br
.ti -1c
.RI "const \fBInteger\fP \fBq\fP"
.br
.ti -1c
.RI "const \fBInteger\fP \fBx0\fP"
.br
.in -1c

Protected Attributes inherited from \fBPublicBlumBlumShub\fP
.in +1c
.ti -1c
.RI "\fBModularArithmetic\fP \fBmodn\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBcurrent\fP"
.br
.ti -1c
.RI "word \fBmaxBits\fP"
.br
.ti -1c
.RI "word \fBbitsLeft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBlumBlumShub\fP with factorization of the modulus\&. 

You should reseed the generator after a fork() to avoid multiple generators with the same internal state\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlumBlumShub::BlumBlumShub (const \fBInteger\fP & p, const \fBInteger\fP & q, const \fBInteger\fP & seed)"

.PP
Construct a \fBBlumBlumShub\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP the first prime factor 
.br
\fIq\fP the second prime factor 
.br
\fIseed\fP the seed for the generator
.RE
.PP
Esure p and q are both primes congruent to 3 mod 4 and at least 512 bits long\&. seed is the secret key and should be about as large as p*q\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool BlumBlumShub::IsRandomAccess () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Determines whether the cipher supports random access\&. 
.PP
\fBReturns\fP
.RS 4
true if the cipher supports random access, false otherwise 
.RE
.PP

.PP
Implements \fBStreamTransformation\fP\&.
.SS "void BlumBlumShub::Seek (\fBlword\fP pos)\fR [virtual]\fP"

.PP
Seek to an absolute position\&. 
.PP
\fBParameters\fP
.RS 4
\fIpos\fP position to seek 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fBNotImplemented\fP\fP 
.RE
.PP
The base class implementation throws \fBNotImplemented\fP\&. The function \fBasserts\fP \fBIsRandomAccess()\fP in debug builds\&. 
.PP
Reimplemented from \fBStreamTransformation\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
