.TH "/home/mock/cryptopp-master/blumshub.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/blumshub.h \- Classes for Blum Blum Shub generator\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'modarith\&.h'\fP
.br
\fR#include 'integer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPublicBlumBlumShub\fP"
.br
.RI "\fBBlumBlumShub\fP without factorization of the modulus\&. "
.ti -1c
.RI "class \fBBlumBlumShub\fP"
.br
.RI "\fBBlumBlumShub\fP with factorization of the modulus\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for Blum Blum Shub generator\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
