.TH "CAST" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAST \- \fBCAST\fP block cipher base\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cast\&.h>\fP
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const \fBword32\fP \fBS\fP [8][256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCAST\fP block cipher base\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
