.TH "/home/mock/cryptopp-master/cast.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/cast.h \- Classes for the CAST-128 and CAST-256 block ciphers\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCAST\fP"
.br
.RI "\fBCAST\fP block cipher base\&. "
.ti -1c
.RI "struct \fBCAST128_Info\fP"
.br
.RI "\fBCAST128\fP block cipher information\&. "
.ti -1c
.RI "class \fBCAST128\fP"
.br
.RI "\fBCAST128\fP block cipher\&. "
.ti -1c
.RI "struct \fBCAST256_Info\fP"
.br
.RI "\fBCAST256\fP block cipher information\&. "
.ti -1c
.RI "class \fBCAST256\fP"
.br
.RI "\fBCAST256\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBCAST128::Encryption\fP \fBCAST128Encryption\fP"
.br
.ti -1c
.RI "typedef \fBCAST128::Decryption\fP \fBCAST128Decryption\fP"
.br
.ti -1c
.RI "typedef \fBCAST256::Encryption\fP \fBCAST256Encryption\fP"
.br
.ti -1c
.RI "typedef \fBCAST256::Decryption\fP \fBCAST256Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the CAST-128 and CAST-256 block ciphers\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.2
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
