.TH "CBC_CTS_Mode_ExternalCipher" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBC_CTS_Mode_ExternalCipher \- CBC mode with ciphertext stealing, external cipher\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <modes\&.h>\fP
.PP
Inherits \fBCipherModeDocumentation\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBCipherModeFinalTemplate_ExternalCipher\fP< \fBCBC_CTS_Encryption\fP > \fBEncryption\fP"
.br
.ti -1c
.RI "typedef \fBCipherModeFinalTemplate_ExternalCipher\fP< \fBCBC_CTS_Decryption\fP > \fBDecryption\fP"
.br
.in -1c

Public Types inherited from \fBSymmetricCipherDocumentation\fP
.in +1c
.ti -1c
.RI "typedef \fBSymmetricCipher\fP \fBEncryption\fP"
.br
.RI "implements the \fBSymmetricCipher\fP interface "
.ti -1c
.RI "typedef \fBSymmetricCipher\fP \fBDecryption\fP"
.br
.RI "implements the \fBSymmetricCipher\fP interface "
.in -1c
.SH "Detailed Description"
.PP 
CBC mode with ciphertext stealing, external cipher\&. 


.PP
\fBSee also\fP
.RS 4
\fRModes of Operation\fP on the Crypto++ wiki\&. 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
