.TH "ChannelSwitchTypedefs" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelSwitchTypedefs
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBChannelRouteIterator\fP, and \fBChannelSwitch\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::pair< \fBBufferedTransformation\fP *, std::string > \fBRoute\fP"
.br
.ti -1c
.RI "typedef std::multimap< std::string, Route > \fBRouteMap\fP"
.br
.ti -1c
.RI "typedef std::pair< \fBBufferedTransformation\fP *, \fBvalue_ptr\fP< std::string > > \fBDefaultRoute\fP"
.br
.ti -1c
.RI "typedef std::list< DefaultRoute > \fBDefaultRouteList\fP"
.br
.ti -1c
.RI "typedef RouteMap::iterator \fBMapIterator\fP"
.br
.ti -1c
.RI "typedef DefaultRouteList::iterator \fBListIterator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
