.TH "/home/mock/cryptopp-master/channels.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/channels.h \- Classes for multiple named channels\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'simple\&.h'\fP
.br
\fR#include 'smartptr\&.h'\fP
.br
\fR#include 'stdcpp\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChannelSwitchTypedefs\fP"
.br
.ti -1c
.RI "class \fBChannelRouteIterator\fP"
.br
.ti -1c
.RI "class \fBChannelSwitch\fP"
.br
.RI "Route input to different and/or multiple channels based on channel ID\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for multiple named channels\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
