.TH "CompileAssert< b >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompileAssert< b >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static char \fBdummy\fP [2 *b\-1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
