.TH "/home/mock/cryptopp-master/config_dll.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/config_dll.h \- Library configuration file\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config_os\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCRYPTOPP_TABLE\fP   extern"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_DLL\fP"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_API\fP"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_EXTERN_DLL_TEMPLATE_CLASS\fP   extern template class CRYPTOPP_DLL"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_DLL_TEMPLATE_CLASS\fP   CRYPTOPP_EXTERN_DLL_TEMPLATE_CLASS"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_EXTERN_STATIC_TEMPLATE_CLASS\fP   extern template class"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_STATIC_TEMPLATE_CLASS\fP   CRYPTOPP_EXTERN_STATIC_TEMPLATE_CLASS"
.br
.in -1c
.SH "Detailed Description"
.PP
Library configuration file\&.

\fR\fBconfig_dll\&.h\fP\fP provides defines for shared objects and dynamic libraries\&. Generally speaking the macros are used to export classes and template classes from the Win32 dynamic link library\&. When not building the Win32 dynamic link library they are mostly an extern template declaration\&.

.PP
In practice they are a furball coughed up by a cat and then peed on by a dog\&. They are awful to get just right because of inconsistent compiler support for extern templates, manual instantiation and the FIPS DLL\&.

.PP
\fR\fBconfig\&.h\fP\fP was split into components in May 2019 to better integrate with Autoconf and its feature tests\&. The splitting occurred so users could continue to include \fR\fBconfig\&.h\fP\fP while allowing Autoconf to write new \fR\fBconfig_asm\&.h\fP\fP and new \fR\fBconfig_cxx\&.h\fP\fP using its feature tests\&.
.PP
\fBNote\fP
.RS 4
You should include \fR\fBconfig\&.h\fP\fP rather than \fR\fBconfig_dll\&.h\fP\fP directly\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRIssue 835, Make config\&.h more autoconf friendly\fP, \fRConfigure\&.sh script\fP, \fRVisual Studio\fP, and \fRFIPS DLL\fP on the Crypto++ wiki
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.3
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
