.TH "/home/mock/cryptopp-master/config_misc.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/config_misc.h \- Library configuration file\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config_asm\&.h'\fP
.br
\fR#include 'config_cxx\&.h'\fP
.br
\fR#include 'config_os\&.h'\fP
.br
\fR#include 'config_ver\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCRYPTOPP_LITTLE_ENDIAN\fP   1"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_DATA_DIR\fP   ''"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_SLOW_ARMV8_SHIFT\fP   1"
.br
.ti -1c
.RI "#define \fBGZIP_OS_CODE\fP   0"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_UNUSED\fP(x)"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_NOINLINE_DOTDOTDOT\fP   \&.\&.\&."
.br
.ti -1c
.RI "#define \fBCRYPTOPP_NOINLINE\fP"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_STATIC_CONSTEXPR\fP   static"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_STATIC_CONST_OR_CONSTEXPR\fP   static const"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_CONST_OR_CONSTEXPR\fP   const"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_CONSTEXPR\fP"
.br
.ti -1c
.RI "#define \fBCRYPTOPP_CONSTANT\fP(x)"
.br
.in -1c
.SH "Detailed Description"
.PP
Library configuration file\&.

\fR\fBconfig_misc\&.h\fP\fP provides miscellaneous defines\&.

.PP
\fR\fBconfig\&.h\fP\fP was split into components in May 2019 to better integrate with Autoconf and its feature tests\&. The splitting occurred so users could continue to include \fR\fBconfig\&.h\fP\fP while allowing Autoconf to write new \fR\fBconfig_asm\&.h\fP\fP and new \fR\fBconfig_cxx\&.h\fP\fP using its feature tests\&.
.PP
\fBNote\fP
.RS 4
You should include \fR\fBconfig\&.h\fP\fP rather than \fR\fBconfig_misc\&.h\fP\fP directly\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fRIssue 835, Make config\&.h more autoconf friendly\fP, \fRConfigure\&.sh script\fP on the Crypto++ wiki
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.3
.RE
.PP

.SH "Macro Definition Documentation"
.PP
.SS "#define CRYPTOPP_CONSTANT( x)"
\fBValue:\fP
.nf
static const int x
.PP
.fi

.SS "#define CRYPTOPP_UNUSED( x)"
\fBValue:\fP
.nf
((void)(x))
.PP
.fi

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
