.TH "/home/mock/cryptopp-master/darn.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/darn.h \- Classes for \fBDARN\fP RNG\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDARN_Err\fP"
.br
.RI "\fBException\fP thrown when a \fBDARN\fP generator encounters a generator related error\&. "
.ti -1c
.RI "class \fBDARN\fP"
.br
.RI "Hardware generated random numbers using \fBDARN\fP instruction\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBDARN\fP RNG\&.


.PP
\fBSee also\fP
.RS 4
\fRPower ISA Version 3\&.0B\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
