.TH "DataDecryptorErr" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataDecryptorErr \- \fBException\fP thrown when LegacyDecryptorWithMAC or DefaultDecryptorWithMAC decryption error is encountered\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default\&.h>\fP
.PP
Inherits \fBException\fP\&.
.PP
Inherited by \fBKeyBadErr\fP, and \fBMACBadErr\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataDecryptorErr\fP (const std::string &s)"
.br
.in -1c

Public Member Functions inherited from \fBException\fP
.in +1c
.ti -1c
.RI "\fBException\fP (\fBErrorType\fP errorType, const std::string &s)"
.br
.RI "Construct a new \fBException\fP\&. "
.ti -1c
.RI "const char * \fBwhat\fP () const  throw ()"
.br
.RI "Retrieves a C-string describing the exception\&. "
.ti -1c
.RI "const std::string & \fBGetWhat\fP () const"
.br
.RI "Retrieves a string describing the exception\&. "
.ti -1c
.RI "void \fBSetWhat\fP (const std::string &s)"
.br
.RI "Sets the error string for the exception\&. "
.ti -1c
.RI "\fBErrorType\fP \fBGetErrorType\fP () const"
.br
.RI "Retrieves the error type for the exception\&. "
.ti -1c
.RI "void \fBSetErrorType\fP (\fBErrorType\fP errorType)"
.br
.RI "Sets the error type for the exceptions\&. "
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBException\fP
.in +1c
.ti -1c
.RI "enum \fBErrorType\fP { \fBNOT_IMPLEMENTED\fP, \fBINVALID_ARGUMENT\fP, \fBCANNOT_FLUSH\fP, \fBDATA_INTEGRITY_CHECK_FAILED\fP, \fBINVALID_DATA_FORMAT\fP, \fBIO_ERROR\fP, \fBOTHER_ERROR\fP }"
.br
.RI "Error types or categories\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBException\fP thrown when LegacyDecryptorWithMAC or DefaultDecryptorWithMAC decryption error is encountered\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
