.TH "DataParametersInfo< BlockSize, KeyLength, DigestSize, SaltSize, Iterations >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataParametersInfo< BlockSize, KeyLength, DigestSize, SaltSize, Iterations > \- \fBAlgorithm\fP information for password-based encryptors and decryptors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <default\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=BlockSize)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (KEYLENGTH=KeyLength)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (SALTLENGTH=SaltSize)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (DIGESTSIZE=DigestSize)"
.br
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (ITERATIONS=Iterations)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned int BlockSize, unsigned int KeyLength, unsigned int DigestSize, unsigned int SaltSize, unsigned int Iterations>
.br
struct DataParametersInfo< BlockSize, KeyLength, DigestSize, SaltSize, Iterations >"\fBAlgorithm\fP information for password-based encryptors and decryptors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
