.TH "DefaultObjectFactory< AbstractClass, ConcreteClass >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultObjectFactory< AbstractClass, ConcreteClass > \- Object factory for registering objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <factory\&.h>\fP
.PP
Inherits \fBObjectFactory< AbstractClass >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "AbstractClass * \fBCreateObject\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class AbstractClass, class ConcreteClass>
.br
class DefaultObjectFactory< AbstractClass, ConcreteClass >"Object factory for registering objects\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIAbstractClass\fP Base class interface of the object 
.br
\fIConcreteClass\fP Class object 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class AbstractClass, class ConcreteClass> AbstractClass * \fBDefaultObjectFactory\fP< AbstractClass, ConcreteClass >::CreateObject () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBObjectFactory< AbstractClass >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
