.TH "Deflator::EncodedMatch" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deflator::EncodedMatch
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBliteralCode\fP: 9"
.br
.ti -1c
.RI "unsigned \fBliteralExtra\fP: 5"
.br
.ti -1c
.RI "unsigned \fBdistanceCode\fP: 5"
.br
.ti -1c
.RI "unsigned \fBdistanceExtra\fP: 13"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
