.TH "/home/mock/cryptopp-master/des.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/des.h \- Classes for \fBDES\fP, 2-key Triple-DES, 3-key Triple-DES and DESX\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRawDES\fP"
.br
.RI "\fBDES\fP block cipher base class\&. "
.ti -1c
.RI "struct \fBDES_Info\fP"
.br
.RI "\fBDES\fP block cipher information\&. "
.ti -1c
.RI "class \fBDES\fP"
.br
.RI "\fBDES\fP block cipher\&. "
.ti -1c
.RI "struct \fBDES_EDE2_Info\fP"
.br
.RI "2-key TripleDES block cipher information "
.ti -1c
.RI "class \fBDES_EDE2\fP"
.br
.RI "2-key TripleDES block cipher "
.ti -1c
.RI "struct \fBDES_EDE3_Info\fP"
.br
.RI "3-key TripleDES block cipher information "
.ti -1c
.RI "class \fBDES_EDE3\fP"
.br
.RI "3-key TripleDES block cipher "
.ti -1c
.RI "struct \fBDES_XEX3_Info\fP"
.br
.RI "DESX block cipher information\&. "
.ti -1c
.RI "class \fBDES_XEX3\fP"
.br
.RI "DESX block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBDES::Encryption\fP \fBDESEncryption\fP"
.br
.ti -1c
.RI "typedef \fBDES::Decryption\fP \fBDESDecryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_EDE2::Encryption\fP \fBDES_EDE2_Encryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_EDE2::Decryption\fP \fBDES_EDE2_Decryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_EDE3::Encryption\fP \fBDES_EDE3_Encryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_EDE3::Decryption\fP \fBDES_EDE3_Decryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_XEX3::Encryption\fP \fBDES_XEX3_Encryption\fP"
.br
.ti -1c
.RI "typedef \fBDES_XEX3::Decryption\fP \fBDES_XEX3_Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBDES\fP, 2-key Triple-DES, 3-key Triple-DES and DESX\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
