.TH "DES_EDE2_Info" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DES_EDE2_Info \- 2-key TripleDES block cipher information  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <des\&.h>\fP
.PP
Inherits \fBFixedBlockSize< 8 >\fP, and \fBFixedKeyLength< 16 >\fP\&.
.PP
Inherited by \fBTwoBases< BlockCipher, DES_EDE2_Info >\fP, and \fBDES_EDE2\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static CRYPTOPP_DLL const char *CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBFixedBlockSize< 8 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=N)"
.br
.RI "The block size of the algorithm provided as a constant\&. "
.in -1c

Public Member Functions inherited from \fBFixedKeyLength< 16 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (KEYLENGTH=N)"
.br
.RI "The default key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "The default key length for the algorithm provided by a static function\&. "
.in -1c
.SH "Detailed Description"
.PP 
2-key TripleDES block cipher information 


.PP
\fBSince\fP
.RS 4
Crypto++ 1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
