.TH "DL_Algorithm_DSA_RFC6979< T, H >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_Algorithm_DSA_RFC6979< T, H > \- \fBDSA\fP signature algorithm based on RFC 6979\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <gfpcrypt\&.h>\fP
.PP
Inherits \fBDL_Algorithm_GDSA< T >\fP, and \fBDeterministicSignatureAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char *CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.ti -1c
.RI "bool \fBIsProbabilistic\fP () const"
.br
.ti -1c
.RI "bool \fBIsDeterministic\fP () const"
.br
.RI "Signature scheme flag\&. "
.ti -1c
.RI "\fBInteger\fP \fBGenerateRandom\fP (const \fBInteger\fP &x, const \fBInteger\fP &q, const \fBInteger\fP &e) const"
.br
.RI "Generate k\&. "
.in -1c

Public Member Functions inherited from \fBDL_Algorithm_GDSA< T >\fP
.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char *CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.ti -1c
.RI "void \fBSign\fP (const \fBDL_GroupParameters\fP< T > &params, const \fBInteger\fP &x, const \fBInteger\fP &k, const \fBInteger\fP &e, \fBInteger\fP &r, \fBInteger\fP &s) const"
.br
.RI "Sign a message using a private key\&. "
.ti -1c
.RI "bool \fBVerify\fP (const \fBDL_GroupParameters\fP< T > &params, const \fBDL_PublicKey\fP< T > &publicKey, const \fBInteger\fP &e, const \fBInteger\fP &r, const \fBInteger\fP &s) const"
.br
.RI "Verify a message using a public key\&. "
.in -1c

Public Member Functions inherited from \fBDL_ElgamalLikeSignatureAlgorithm< T >\fP
.in +1c
.ti -1c
.RI "virtual \fBInteger\fP \fBRecoverPresignature\fP (const \fBDL_GroupParameters\fP< T > &params, const \fBDL_PublicKey\fP< T > &publicKey, const \fBInteger\fP &r, const \fBInteger\fP &s) const"
.br
.RI "Recover a Presignature\&. "
.ti -1c
.RI "virtual size_t \fBRLen\fP (const \fBDL_GroupParameters\fP< T > &params) const"
.br
.RI "Retrieve R length\&. "
.ti -1c
.RI "virtual size_t \fBSLen\fP (const \fBDL_GroupParameters\fP< T > &params) const"
.br
.RI "Retrieve S length\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBInteger\fP \fBbits2int\fP (const \fBSecByteBlock\fP &bits, size_t qlen) const"
.br
.ti -1c
.RI "\fBSecByteBlock\fP \fBint2octets\fP (const \fBInteger\fP &val, size_t rlen) const"
.br
.ti -1c
.RI "\fBSecByteBlock\fP \fBbits2octets\fP (const \fBSecByteBlock\fP &in, const \fBInteger\fP &q) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class H>
.br
class DL_Algorithm_DSA_RFC6979< T, H >"\fBDSA\fP signature algorithm based on RFC 6979\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP FieldElement type or class 
.br
\fIH\fP \fBHashTransformation\fP derived class
.RE
.PP
FieldElement \fRT\fP can be \fBInteger\fP, \fBECP\fP or \fBEC2N\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fRRFC 6979, Deterministic Usage of the Digital Signature Algorithm (DSA) and Elliptic Curve Digital Signature Algorithm (ECDSA)\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class T, class H> \fBInteger\fP \fBDL_Algorithm_DSA_RFC6979\fP< T, H >::GenerateRandom (const \fBInteger\fP & x, const \fBInteger\fP & q, const \fBInteger\fP & e) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Generate k\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP private key 
.br
\fIq\fP subgroup generator 
.br
\fIe\fP encoded message 
.RE
.PP

.PP
Implements \fBDeterministicSignatureAlgorithm\fP\&.
.SS "template<class T, class H> bool \fBDL_Algorithm_DSA_RFC6979\fP< T, H >::IsDeterministic () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Signature scheme flag\&. 
.PP
\fBReturns\fP
.RS 4
true if the signature scheme is deterministic, false otherwise
.RE
.PP
\fBIsDeterministic()\fP is provided for DL signers\&. It is used by RFC 6979 signature schemes\&. 
.PP
Reimplemented from \fBDL_ElgamalLikeSignatureAlgorithm< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
