.TH "DL_CryptoKeys_ElGamal" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_CryptoKeys_ElGamal
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <gfpcrypt\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDL_GroupParameters_ElGamal\fP \fBGroupParameters\fP"
.br
.ti -1c
.RI "typedef \fBDL_PublicKey_GFP\fP< \fBGroupParameters\fP > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_GFP\fP< \fBGroupParameters\fP > \fBPrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBElGamal\fP encryption keys for safe interop 
.PP
\fBSee also\fP
.RS 4
\fROn the (in)security of ElGamal in OpenPGP\fP, \fRIssue 1059\fP, \fRCVE-2021-40530\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.6 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
