.TH "DL_ES< KEYS, AA, DA, EA, ALG_INFO >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_ES< KEYS, AA, DA, EA, ALG_INFO > \- Discrete Log (DL) encryption scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits KEYS\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_DecryptorImpl\fP< \fBSchemeOptions\fP > > \fBDecryptor\fP"
.br
.RI "implements \fBPK_Decryptor\fP interface "
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_EncryptorImpl\fP< \fBSchemeOptions\fP > > \fBEncryptor\fP"
.br
.RI "implements \fBPK_Encryptor\fP interface "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class KEYS, class AA, class DA, class EA, class ALG_INFO>
.br
class DL_ES< KEYS, AA, DA, EA, ALG_INFO >"Discrete Log (DL) encryption scheme\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIKEYS\fP keys used in the encryption scheme 
.br
\fIAA\fP key agreement algorithm 
.br
\fIDA\fP key derivation algorithm 
.br
\fIEA\fP encryption algorithm 
.br
\fIALG_INFO\fP algorithm information 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
