.TH "DL_Keys_ECGDSA< EC >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_Keys_ECGDSA< EC > \- Elliptic Curve German \fBDSA\fP keys for ISO/IEC 15946\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <eccrypto\&.h>\fP
.PP
Inherited by \fBDL_SS< DL_Keys_ECGDSA< EC >, DL_Algorithm_ECGDSA< EC >, DL_SignatureMessageEncodingMethod_DSA, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDL_PublicKey_ECGDSA\fP< EC > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_ECGDSA\fP< EC > \fBPrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EC>
.br
struct DL_Keys_ECGDSA< EC >"Elliptic Curve German \fBDSA\fP keys for ISO/IEC 15946\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIEC\fP elliptic curve field 
.RE
.PP
\fBSee also\fP
.RS 4
\fBECGDSA\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
