.TH "DL_KeyDerivationAlgorithm< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_KeyDerivationAlgorithm< T > \- Interface for key derivation algorithms used in DL cryptosystems\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherited by \fBDL_KeyDerivationAlgorithm_P1363< T, DHAES_MODE, KDF >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBParameterSupported\fP (const char *name) const"
.br
.ti -1c
.RI "virtual void \fBDerive\fP (const \fBDL_GroupParameters\fP< T > &groupParams, \fBbyte\fP *derivedKey, size_t derivedLength, const T &agreedElement, const T &ephemeralPublicKey, const \fBNameValuePairs\fP &derivationParams) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class DL_KeyDerivationAlgorithm< T >"Interface for key derivation algorithms used in DL cryptosystems\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Field element type or class
.RE
.PP
Field element \fRT\fP can be \fBInteger\fP, \fBECP\fP or \fBEC2N\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBDLIES\fP, \fBECIES\fP, \fBECIES_P1363\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
