.TH "DL_Keys_EC< EC >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_Keys_EC< EC > \- Elliptic Curve Discrete Log (DL) keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <eccrypto\&.h>\fP
.PP
Inherited by \fBDL_ES< DL_Keys_EC< EC >, DL_KeyAgreementAlgorithm_DH< EC::Point, NoCofactorMultiplication >, DL_KeyDerivationAlgorithm_P1363< EC::Point, true, P1363_KDF2< SHA1 > >, DL_EncryptionAlgorithm_Xor< HMAC< SHA1 >, true, false >, ECIES< EC > >\fP, \fBDL_ES< DL_Keys_EC< EC >, DL_KeyAgreementAlgorithm_DH< EC::Point, NoCofactorMultiplication >, DL_KeyDerivationAlgorithm_P1363< EC::Point, true, P1363_KDF2< SHA1 > >, DL_EncryptionAlgorithm_Xor< HMAC< NULL_Hash >, true, false >, ECIES< EC > >\fP, \fBDL_ES< DL_Keys_EC< EC >, DL_KeyAgreementAlgorithm_DH< EC::Point, NoCofactorMultiplication >, DL_KeyDerivationAlgorithm_P1363< EC::Point, false, P1363_KDF2< SHA1 > >, DL_EncryptionAlgorithm_Xor< HMAC< SHA1 >, false, true >, ECIES< EC > >\fP, and \fBDL_SS< DL_Keys_EC< EC >, DL_Algorithm_ECNR< EC >, DL_SignatureMessageEncodingMethod_NR, SHA1 >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDL_PublicKey_EC\fP< EC > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_EC\fP< EC > \fBPrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EC>
.br
struct DL_Keys_EC< EC >"Elliptic Curve Discrete Log (DL) keys\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIEC\fP elliptic curve field 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
