.TH "DL_SignatureMessageEncodingMethod_DSA" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_SignatureMessageEncodingMethod_DSA \- Interface for message encoding method for public key signature schemes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits \fBPK_DeterministicSignatureMessageEncodingMethod\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBComputeMessageRepresentative\fP (\fBRandomNumberGenerator\fP &rng, const \fBbyte\fP *recoverableMessage, size_t recoverableMessageLength, \fBHashTransformation\fP &hash, HashIdentifier hashIdentifier, bool messageEmpty, \fBbyte\fP *representative, size_t representativeBitLength) const"
.br
.in -1c

Public Member Functions inherited from \fBPK_DeterministicSignatureMessageEncodingMethod\fP
.in +1c
.ti -1c
.RI "bool \fBVerifyMessageRepresentative\fP (\fBHashTransformation\fP &hash, HashIdentifier hashIdentifier, bool messageEmpty, \fBbyte\fP *representative, size_t representativeBitLength) const"
.br
.in -1c

Public Member Functions inherited from \fBPK_SignatureMessageEncodingMethod\fP
.in +1c
.ti -1c
.RI "virtual size_t \fBMinRepresentativeBitLength\fP (size_t hashIdentifierLength, size_t digestLength) const"
.br
.ti -1c
.RI "virtual size_t \fBMaxRecoverableLength\fP (size_t representativeBitLength, size_t hashIdentifierLength, size_t digestLength) const"
.br
.ti -1c
.RI "bool \fBIsProbabilistic\fP () const"
.br
.RI "Determines whether an encoding method requires a random number generator\&. "
.ti -1c
.RI "bool \fBAllowNonrecoverablePart\fP () const"
.br
.ti -1c
.RI "virtual bool \fBRecoverablePartFirst\fP () const"
.br
.ti -1c
.RI "virtual void \fBProcessSemisignature\fP (\fBHashTransformation\fP &hash, const \fBbyte\fP *semisignature, size_t semisignatureLength) const"
.br
.ti -1c
.RI "virtual void \fBProcessRecoverableMessage\fP (\fBHashTransformation\fP &hash, const \fBbyte\fP *recoverableMessage, size_t recoverableMessageLength, const \fBbyte\fP *presignature, size_t presignatureLength, \fBSecByteBlock\fP &semisignature) const"
.br
.ti -1c
.RI "virtual \fBDecodingResult\fP \fBRecoverMessageFromRepresentative\fP (\fBHashTransformation\fP &hash, HashIdentifier hashIdentifier, bool messageEmpty, \fBbyte\fP *representative, size_t representativeBitLength, \fBbyte\fP *recoveredMessage) const"
.br
.ti -1c
.RI "virtual \fBDecodingResult\fP \fBRecoverMessageFromSemisignature\fP (\fBHashTransformation\fP &hash, HashIdentifier hashIdentifier, const \fBbyte\fP *presignature, size_t presignatureLength, const \fBbyte\fP *semisignature, size_t semisignatureLength, \fBbyte\fP *recoveredMessage) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for message encoding method for public key signature schemes\&. 

\fBDL_SignatureMessageEncodingMethod_DSA\fP provides interfaces for message encoding method for \fBDSA\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void DL_SignatureMessageEncodingMethod_DSA::ComputeMessageRepresentative (\fBRandomNumberGenerator\fP & rng, const \fBbyte\fP * recoverableMessage, size_t recoverableMessageLength, \fBHashTransformation\fP & hash, HashIdentifier hashIdentifier, bool messageEmpty, \fBbyte\fP * representative, size_t representativeBitLength) const\fR [virtual]\fP"

.PP
Implements \fBPK_SignatureMessageEncodingMethod\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
