.TH "DL_SchemeOptionsBase< T1, T2 >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_SchemeOptionsBase< T1, T2 > \- Discrete Log (DL) scheme options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T1 \fBAlgorithmInfo\fP"
.br
.ti -1c
.RI "typedef T2 \fBGroupParameters\fP"
.br
.ti -1c
.RI "typedef GroupParameters::Element \fBElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T1, class T2>
.br
struct DL_SchemeOptionsBase< T1, T2 >"Discrete Log (DL) scheme options\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT1\fP algorithm information 
.br
\fIT2\fP group parameters for the scheme 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
