.TH "DL_SignatureKeys_LUC" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_SignatureKeys_LUC \- \fBLUC\fP signature keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <luc\&.h>\fP
.PP
Inherited by \fBDL_SS< DL_SignatureKeys_LUC, DL_Algorithm_LUC_HMP, DL_SignatureMessageEncodingMethod_DSA, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDL_GroupParameters_LUC\fP \fBGroupParameters\fP"
.br
.ti -1c
.RI "typedef \fBDL_PublicKey_GFP\fP< \fBGroupParameters\fP > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_GFP\fP< \fBGroupParameters\fP > \fBPrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLUC\fP signature keys\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
