.TH "DL_SignatureKeys_GFP" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DL_SignatureKeys_GFP \- Discrete Log (DL) signing/verification keys in GF(p) groups\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <gfpcrypt\&.h>\fP
.PP
Inherited by \fBDL_SS< DL_SignatureKeys_GFP, DL_Algorithm_DSA_RFC6979< Integer, H >, DL_SignatureMessageEncodingMethod_DSA, H, DSA_RFC6979< H > >\fP, \fBDL_SS< DL_SignatureKeys_GFP, DL_Algorithm_GDSA< Integer >, DL_SignatureMessageEncodingMethod_DSA, H >\fP, and \fBDL_SS< DL_SignatureKeys_GFP, DL_Algorithm_NR< Integer >, DL_SignatureMessageEncodingMethod_NR, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDL_GroupParameters_GFP\fP \fBGroupParameters\fP"
.br
.ti -1c
.RI "typedef \fBDL_PublicKey_GFP\fP< \fBGroupParameters\fP > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_GFP\fP< \fBGroupParameters\fP > \fBPrivateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Discrete Log (DL) signing/verification keys in GF(p) groups\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
