.TH "/home/mock/cryptopp-master/dmac.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/dmac.h \- Classes for \fBDMAC\fP message authentication code\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cbcmac\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDMAC_Base< T >\fP"
.br
.RI "\fBDMAC\fP message authentication code base class\&. "
.ti -1c
.RI "class \fBDMAC< T >\fP"
.br
.RI "\fBDMAC\fP message authentication code\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBDMAC\fP message authentication code\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
