.TH "DWord" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DWord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDWord\fP (word low)"
.br
.ti -1c
.RI "\fBDWord\fP (word low, word high)"
.br
.ti -1c
.RI "\fBDWord\fP & \fBoperator+=\fP (word a)"
.br
.ti -1c
.RI "\fBDWord\fP \fBoperator+\fP (word a)"
.br
.ti -1c
.RI "\fBDWord\fP \fBoperator\-\fP (\fBDWord\fP a)"
.br
.ti -1c
.RI "\fBDWord\fP \fBoperator\-\fP (word a)"
.br
.ti -1c
.RI "word \fBoperator/\fP (word divisor)"
.br
.ti -1c
.RI "word \fBoperator%\fP (word a)"
.br
.ti -1c
.RI "bool \fBoperator!\fP () const"
.br
.ti -1c
.RI "word \fBGetLowHalf\fP () const"
.br
.ti -1c
.RI "word \fBGetHighHalf\fP () const"
.br
.ti -1c
.RI "word \fBGetHighHalfAsBorrow\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDWord\fP \fBMultiply\fP (word a, word b)"
.br
.ti -1c
.RI "static \fBDWord\fP \fBMultiplyAndAdd\fP (word a, word b, word c)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
