.TH "ECIES_NULLDigest< EC, HASH, COFACTOR_OPTION, DHAES_MODE, LABEL_OCTETS >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECIES_NULLDigest< EC, HASH, COFACTOR_OPTION, DHAES_MODE, LABEL_OCTETS >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDL_ES< DL_Keys_EC< EC >, DL_KeyAgreementAlgorithm_DH< EC::Point, NoCofactorMultiplication >, DL_KeyDerivationAlgorithm_P1363< EC::Point, true, P1363_KDF2< SHA1 > >, DL_EncryptionAlgorithm_Xor< HMAC< NULL_Hash >, true, false >, ECIES< EC > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char *CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBDL_ES< DL_Keys_EC< EC >, DL_KeyAgreementAlgorithm_DH< EC::Point, NoCofactorMultiplication >, DL_KeyDerivationAlgorithm_P1363< EC::Point, true, P1363_KDF2< SHA1 > >, DL_EncryptionAlgorithm_Xor< HMAC< NULL_Hash >, true, false >, ECIES< EC > >\fP
.in +1c
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_DecryptorImpl\fP< \fBSchemeOptions\fP > > \fBDecryptor\fP"
.br
.RI "implements \fBPK_Decryptor\fP interface "
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_EncryptorImpl\fP< \fBSchemeOptions\fP > > \fBEncryptor\fP"
.br
.RI "implements \fBPK_Encryptor\fP interface "
.in -1c

Public Types inherited from \fBDL_Keys_EC< EC >\fP
.in +1c
.ti -1c
.RI "typedef \fBDL_PublicKey_EC\fP< EC > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_EC\fP< EC > \fBPrivateKey\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
