.TH "ECNR< EC, H >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECNR< EC, H > \- Elliptic Curve \fBNR\fP (\fBECNR\fP) signature scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <eccrypto\&.h>\fP
.PP
Inherits \fBDL_SS< DL_Keys_EC< EC >, DL_Algorithm_ECNR< EC >, DL_SignatureMessageEncodingMethod_NR, SHA1 >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBDL_SS< DL_Keys_EC< EC >, DL_Algorithm_ECNR< EC >, DL_SignatureMessageEncodingMethod_NR, SHA1 >\fP
.in +1c
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_SignerImpl\fP< \fBSchemeOptions\fP > > \fBSigner\fP"
.br
.RI "implements \fBPK_Signer\fP interface "
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBDL_VerifierImpl\fP< \fBSchemeOptions\fP > > \fBVerifier\fP"
.br
.RI "implements \fBPK_Verifier\fP interface "
.in -1c

Public Types inherited from \fBDL_Keys_EC< EC >\fP
.in +1c
.ti -1c
.RI "typedef \fBDL_PublicKey_EC\fP< EC > \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBDL_PrivateKey_EC\fP< EC > \fBPrivateKey\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBDL_SS< DL_Keys_EC< EC >, DL_Algorithm_ECNR< EC >, DL_SignatureMessageEncodingMethod_NR, SHA1 >\fP
.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EC, class H = SHA1>
.br
struct ECNR< EC, H >"Elliptic Curve \fBNR\fP (\fBECNR\fP) signature scheme\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIEC\fP elliptic curve field 
.br
\fIH\fP \fBHashTransformation\fP derived class 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
