.TH "/home/mock/cryptopp-master/ecpoint.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/ecpoint.h \- Classes for Elliptic Curve points\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'integer\&.h'\fP
.br
\fR#include 'algebra\&.h'\fP
.br
\fR#include 'gf2n\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBECPPoint\fP"
.br
.RI "Elliptical Curve Point over GF(p), where p is prime\&. "
.ti -1c
.RI "struct \fBEC2NPoint\fP"
.br
.RI "Elliptical Curve Point over GF(2^n) "
.ti -1c
.RI "class \fBEncodedPoint< Point >\fP"
.br
.RI "Abstract class for encoding and decoding ellicptic curve points\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CRYPTOPP_DLL_TEMPLATE_CLASS \fBAbstractGroup< ECPPoint >\fP"
.br
.ti -1c
.RI "CRYPTOPP_DLL_TEMPLATE_CLASS \fBAbstractGroup< EC2NPoint >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for Elliptic Curve points\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
