.TH "EcRecommendedParameters< ECP >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcRecommendedParameters< ECP >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEcRecommendedParameters\fP (const \fBOID\fP &oid, const char *p, const char *a, const char *b, const char *g, const char *n, unsigned int h)"
.br
.ti -1c
.RI "\fBECP\fP * \fBNewEC\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOID\fP \fBoid\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.ti -1c
.RI "const char * \fBa\fP"
.br
.ti -1c
.RI "const char * \fBb\fP"
.br
.ti -1c
.RI "const char * \fBg\fP"
.br
.ti -1c
.RI "const char * \fBn\fP"
.br
.ti -1c
.RI "unsigned int \fBh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
