.TH "ed25519" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ed25519 \- Ed25519 signature scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <xed25519\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBed25519Signer\fP \fBSigner\fP"
.br
.RI "\fBed25519\fP \fBSigner\fP "
.ti -1c
.RI "typedef \fBed25519Verifier\fP \fBVerifier\fP"
.br
.RI "\fBed25519\fP \fBVerifier\fP "
.in -1c
.SH "Detailed Description"
.PP 
Ed25519 signature scheme\&. 


.PP
\fBSee also\fP
.RS 4
\fREd25519\fP on the Crypto++ wiki\&. 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
