.TH "/home/mock/cryptopp-master/elgamal.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/elgamal.h \- Classes and functions for \fBElGamal\fP key agreement and encryption schemes\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'modexppc\&.h'\fP
.br
\fR#include 'integer\&.h'\fP
.br
\fR#include 'gfpcrypt\&.h'\fP
.br
\fR#include 'pubkey\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br
\fR#include 'oids\&.h'\fP
.br
\fR#include 'dsa\&.h'\fP
.br
\fR#include 'asn\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElGamalBase\fP"
.br
.RI "\fBElGamal\fP key agreement and encryption schemes base class\&. "
.ti -1c
.RI "class \fBElGamalObjectImpl< BASE, SCHEME_OPTIONS, KEY >\fP"
.br
.RI "\fBElGamal\fP key agreement and encryption schemes default implementation\&. "
.ti -1c
.RI "struct \fBDL_PublicKey_ElGamal< BASE >\fP"
.br
.RI "\fBElGamal\fP Public Key adapter\&. "
.ti -1c
.RI "struct \fBDL_PrivateKey_ElGamal< BASE >\fP"
.br
.RI "\fBElGamal\fP Private Key adapter\&. "
.ti -1c
.RI "struct \fBElGamalKeys\fP"
.br
.RI "\fBElGamal\fP key agreement and encryption schemes keys\&. "
.ti -1c
.RI "struct \fBElGamal\fP"
.br
.RI "\fBElGamal\fP encryption scheme with non-standard padding\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBElGamal::Encryptor\fP \fBElGamalEncryptor\fP"
.br
.ti -1c
.RI "typedef \fBElGamal::Decryptor\fP \fBElGamalDecryptor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes and functions for \fBElGamal\fP key agreement and encryption schemes\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
