.TH "Empty" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Empty \- An \fBEmpty\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <misc\&.h>\fP
.PP
Inherited by \fBAbstractPolicyHolder< POLICY_INTERFACE, BASE >\fP\&.
.SH "Detailed Description"
.PP 
An \fBEmpty\fP class\&. 

The \fBEmpty\fP class can be used as a template parameter \fRBASE\fP when no base class exists\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
