.TH "EMSA2HashId< H >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EMSA2HashId< H > \- EMSA2 hash identifier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <emsa2\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBbyte\fP \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class H>
.br
class EMSA2HashId< H >"EMSA2 hash identifier\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIH\fP \fBHashTransformation\fP derived class 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
