.TH "EMSA2HashIdLookup< BASE >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EMSA2HashIdLookup< BASE > \- EMSA2 padding method\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <emsa2\&.h>\fP
.PP
Inherits BASE\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHashIdentifierLookup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class BASE>
.br
class EMSA2HashIdLookup< BASE >"EMSA2 padding method\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIBASE\fP Message encoding method 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
