.TH "EncryptionStandard" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncryptionStandard \- Base class for public key encryption standard classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherited by \fBOAEP< H, MGF >\fP, \fBOAEP< H, MGF >\fP, and \fBPKCS1v15\fP\&.
.SH "Detailed Description"
.PP 
Base class for public key encryption standard classes\&. 

These classes are used to select from variants of algorithms\&. Not all standards apply to all algorithms\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
