.TH "EnumToType< ENUM_TYPE, VALUE >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnumToType< ENUM_TYPE, VALUE > \- Converts an enumeration to a type suitable for use as a template parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cryptlib\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ENUM_TYPE \fBToEnum\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ENUM_TYPE, int VALUE>
.br
struct EnumToType< ENUM_TYPE, VALUE >"Converts an enumeration to a type suitable for use as a template parameter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
