.TH "ESIGN_Keys" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESIGN_Keys \- \fBESIGN\fP keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <esign\&.h>\fP
.PP
Inherited by \fBTF_SS< ESIGN_Keys, P1363_EMSA5, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBESIGNFunction\fP \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBInvertibleESIGNFunction\fP \fBPrivateKey\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char * \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBESIGN\fP keys\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
