.TH "/home/mock/cryptopp-master/fhmqv.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/fhmqv.h \- Classes for Fully Hashed Menezes-Qu-Vanstone key agreement in GF(p)

.SH SYNOPSIS
.br
.PP
\fR#include 'gfpcrypt\&.h'\fP
.br
\fR#include 'algebra\&.h'\fP
.br
\fR#include 'sha\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFHMQV_Domain< GROUP_PARAMETERS, COFACTOR_OPTION, HASH >\fP"
.br
.RI "Fully Hashed Menezes-Qu-Vanstone in GF(p) "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBFHMQV_Domain\fP< \fBDL_GroupParameters_GFP_DefaultSafePrime\fP > \fBFHMQV\fP"
.br
.RI "Fully Hashed Menezes-Qu-Vanstone in GF(p) "
.in -1c
.SH "Detailed Description"
.PP
Classes for Fully Hashed Menezes-Qu-Vanstone key agreement in GF(p)


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SH "Typedef Documentation"
.PP
.SS "typedef \fBFHMQV_Domain\fP<\fBDL_GroupParameters_GFP_DefaultSafePrime\fP> \fBFHMQV\fP"

.PP
Fully Hashed Menezes-Qu-Vanstone in GF(p) This implementation follows Augustin P\&. Sarr and Philippe Elbaz–Vincent, and Jean–Claude Bajard's \fRA Secure and Efficient Authenticated Diffie-Hellman Protocol\fP\&. Note: this is \fBFHMQV\fP, Protocol 5, from page 11; and not FHMQV-C\&.
.PP
\fBSee also\fP
.RS 4
\fBFHMQV\fP, \fBMQV_Domain\fP, \fBFHMQV_Domain\fP, \fBAuthenticatedKeyAgreementDomain\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
