.TH "/home/mock/cryptopp-master/files.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/files.h \- Classes providing file-based library services\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'filters\&.h'\fP
.br
\fR#include 'argnames\&.h'\fP
.br
\fR#include 'smartptr\&.h'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileStore\fP"
.br
.RI "Implementation of \fBStore\fP interface\&. "
.ti -1c
.RI "class \fBFileStore::Err\fP"
.br
.RI "\fBException\fP thrown when file-based error is encountered\&. "
.ti -1c
.RI "class \fBFileStore::OpenErr\fP"
.br
.RI "\fBException\fP thrown when file-based open error is encountered\&. "
.ti -1c
.RI "class \fBFileStore::ReadErr\fP"
.br
.RI "\fBException\fP thrown when file-based read error is encountered\&. "
.ti -1c
.RI "class \fBFileSource\fP"
.br
.RI "Implementation of \fBStore\fP interface\&. "
.ti -1c
.RI "class \fBFileSink\fP"
.br
.RI "Implementation of \fBStore\fP interface\&. "
.ti -1c
.RI "class \fBFileSink::Err\fP"
.br
.RI "\fBException\fP thrown when file-based error is encountered\&. "
.ti -1c
.RI "class \fBFileSink::OpenErr\fP"
.br
.RI "\fBException\fP thrown when file-based open error is encountered\&. "
.ti -1c
.RI "class \fBFileSink::WriteErr\fP"
.br
.RI "\fBException\fP thrown when file-based write error is encountered\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes providing file-based library services\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 1\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
