.TH "FixedBlockSize< N >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedBlockSize< N > \- Inherited by algorithms with fixed block size\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <seckey\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=N)"
.br
.RI "The block size of the algorithm provided as a constant\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned int N>
.br
class FixedBlockSize< N >"Inherited by algorithms with fixed block size\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIN\fP the blocksize of the algorithm 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
