.TH "FixedRounds< R >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedRounds< R > \- Inherited by algorithms with fixed number of rounds\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <seckey\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (ROUNDS=R)"
.br
.RI "The number of rounds for the algorithm provided as a constant\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned int R>
.br
class FixedRounds< R >"Inherited by algorithms with fixed number of rounds\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIR\fP the number of rounds used by the algorithm 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
