.TH "FixedSizeAllocatorWithCleanup< T, S, A, T_Align16 >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedSizeAllocatorWithCleanup< T, S, A, T_Align16 > \- Static secure memory block with cleanup\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <secblock\&.h>\fP
.PP
Inherits \fBAllocatorBase< T >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBAllocatorBase< T >\fP
.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef T * \fBpointer\fP"
.br
.ti -1c
.RI "typedef const T * \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef T & \fBreference\fP"
.br
.ti -1c
.RI "typedef const T & \fBconst_reference\fP"
.br
.in -1c

Public Member Functions inherited from \fBAllocatorBase< T >\fP
.in +1c
.ti -1c
.RI "pointer \fBaddress\fP (reference r) const"
.br
.ti -1c
.RI "const_pointer \fBaddress\fP (const_reference r) const"
.br
.ti -1c
.RI "void \fBconstruct\fP (pointer p, const T &val)"
.br
.ti -1c
.RI "void \fBdestroy\fP (pointer p)"
.br
.ti -1c
.RI "CRYPTOPP_CONSTEXPR size_type \fBmax_size\fP () const"
.br
.RI "Returns the maximum number of elements the allocator can provide\&. "
.in -1c

Static Public Attributes inherited from \fBAllocatorBase< T >\fP
.in +1c
.ti -1c
.RI "static const size_type \fBELEMS_MAX\fP = SIZE_MAX/sizeof(T)"
.br
.RI "Returns the maximum number of elements the allocator can provide\&. "
.in -1c

Static Protected Member Functions inherited from \fBAllocatorBase< T >\fP
.in +1c
.ti -1c
.RI "static void \fBCheckSize\fP (size_t size)"
.br
.RI "Verifies the allocator can satisfy a request based on size\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, size_t S, class A = NullAllocator<T>, bool T_Align16 = false>
.br
class FixedSizeAllocatorWithCleanup< T, S, A, T_Align16 >"Static secure memory block with cleanup\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP class or type 
.br
\fIS\fP fixed-size of the stack-based memory block, in elements 
.br
\fIT_Align16\fP boolean that determines whether allocations should be aligned on a 16-byte boundary
.RE
.PP
\fBFixedSizeAllocatorWithCleanup\fP provides a fixed-size, stack- based allocation at compile time\&. The class can grow its memory block at runtime if a suitable allocator is available\&. If size grows beyond S and a suitable allocator is available, then the statically allocated array is obsoleted\&. 
.PP
\fBNote\fP
.RS 4
This allocator can't be used with standard collections because they require that all objects of the same allocator type are equivalent\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
