.TH "FixedSizeSecBlock< T, S, A >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedSizeSecBlock< T, S, A > \- Fixed size stack-based \fBSecBlock\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <secblock\&.h>\fP
.PP
Inherits \fBSecBlock< T, A >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFixedSizeSecBlock\fP ()"
.br
.RI "Construct a \fBFixedSizeSecBlock\fP\&. "
.in -1c

Public Member Functions inherited from \fBSecBlock< T, A >\fP
.in +1c
.ti -1c
.RI "\fBSecBlock\fP (size_type \fBsize\fP=0)"
.br
.RI "Construct a \fBSecBlock\fP with space for size elements\&. "
.ti -1c
.RI "\fBSecBlock\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Copy construct a \fBSecBlock\fP from another \fBSecBlock\fP\&. "
.ti -1c
.RI "\fBSecBlock\fP (const T *ptr, size_type len)"
.br
.RI "Construct a \fBSecBlock\fP from an array of elements\&. "
.ti -1c
.RI "\fBoperator const void *\fP () const"
.br
.RI "Cast operator\&. "
.ti -1c
.RI "\fBoperator void *\fP ()"
.br
.RI "Cast operator\&. "
.ti -1c
.RI "\fBoperator const T *\fP () const"
.br
.RI "Cast operator\&. "
.ti -1c
.RI "\fBoperator T*\fP ()"
.br
.RI "Cast operator\&. "
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.RI "Provides an iterator pointing to the first element in the memory block\&. "
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.RI "Provides a constant iterator pointing to the first element in the memory block\&. "
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.RI "Provides an iterator pointing beyond the last element in the memory block\&. "
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.RI "Provides a constant iterator pointing beyond the last element in the memory block\&. "
.ti -1c
.RI "A::pointer \fBdata\fP ()"
.br
.RI "Provides a pointer to the first element in the memory block\&. "
.ti -1c
.RI "A::const_pointer \fBdata\fP () const"
.br
.RI "Provides a pointer to the first element in the memory block\&. "
.ti -1c
.RI "size_type \fBsize\fP () const"
.br
.RI "Provides the count of elements in the \fBSecBlock\fP\&. "
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "Determines if the \fBSecBlock\fP is empty\&. "
.ti -1c
.RI "\fBbyte\fP * \fBBytePtr\fP ()"
.br
.RI "Provides a byte pointer to the first element in the memory block\&. "
.ti -1c
.RI "const \fBbyte\fP * \fBBytePtr\fP () const"
.br
.RI "Return a byte pointer to the first element in the memory block\&. "
.ti -1c
.RI "size_type \fBSizeInBytes\fP () const"
.br
.RI "Provides the number of bytes in the \fBSecBlock\fP\&. "
.ti -1c
.RI "void \fBAssign\fP (const T *ptr, size_type len)"
.br
.RI "Set contents and size from an array\&. "
.ti -1c
.RI "void \fBAssign\fP (size_type count, T value)"
.br
.RI "Set contents from a value\&. "
.ti -1c
.RI "void \fBAssign\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Copy contents from another \fBSecBlock\fP\&. "
.ti -1c
.RI "void \fBAppend\fP (const T *ptr, size_type len)"
.br
.RI "Append contents from an array\&. "
.ti -1c
.RI "void \fBAppend\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Append contents from another \fBSecBlock\fP\&. "
.ti -1c
.RI "void \fBAppend\fP (size_type count, T value)"
.br
.RI "Append contents from a value\&. "
.ti -1c
.RI "void \fBSetMark\fP (size_t count)"
.br
.RI "Sets the number of elements to zeroize\&. "
.ti -1c
.RI "\fBSecBlock\fP< T, A > & \fBoperator=\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Assign contents from another \fBSecBlock\fP\&. "
.ti -1c
.RI "\fBSecBlock\fP< T, A > & \fBoperator+=\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Append contents from another \fBSecBlock\fP\&. "
.ti -1c
.RI "\fBSecBlock\fP< T, A > \fBoperator+\fP (const \fBSecBlock\fP< T, A > &t)"
.br
.RI "Construct a \fBSecBlock\fP from this and another \fBSecBlock\fP\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSecBlock\fP< T, A > &t) const"
.br
.RI "Bitwise compare two SecBlocks\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSecBlock\fP< T, A > &t) const"
.br
.RI "Bitwise compare two SecBlocks\&. "
.ti -1c
.RI "void \fBNew\fP (size_type newSize)"
.br
.RI "Change size without preserving contents\&. "
.ti -1c
.RI "void \fBCleanNew\fP (size_type newSize)"
.br
.RI "Change size without preserving contents\&. "
.ti -1c
.RI "void \fBGrow\fP (size_type newSize)"
.br
.RI "Change size and preserve contents\&. "
.ti -1c
.RI "void \fBCleanGrow\fP (size_type newSize)"
.br
.RI "Change size and preserve contents\&. "
.ti -1c
.RI "void \fBresize\fP (size_type newSize)"
.br
.RI "Change size and preserve contents\&. "
.ti -1c
.RI "void \fBswap\fP (\fBSecBlock\fP< T, A > &b)"
.br
.RI "Swap contents with another \fBSecBlock\fP\&. "
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBSecBlock< T, A >\fP
.in +1c
.ti -1c
.RI "typedef A::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef A::pointer \fBiterator\fP"
.br
.ti -1c
.RI "typedef A::const_pointer \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef A::size_type \fBsize_type\fP"
.br
.in -1c

Static Public Attributes inherited from \fBSecBlock< T, A >\fP
.in +1c
.ti -1c
.RI "static const size_type \fBELEMS_MAX\fP = SIZE_MAX/sizeof(T)"
.br
.RI "Returns the maximum number of elements the block can hold\&. "
.in -1c

Protected Attributes inherited from \fBSecBlock< T, A >\fP
.in +1c
.ti -1c
.RI "A \fBm_alloc\fP"
.br
.ti -1c
.RI "size_type \fBm_mark\fP"
.br
.ti -1c
.RI "size_type \fBm_size\fP"
.br
.ti -1c
.RI "T * \fBm_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, unsigned int S, class A = FixedSizeAllocatorWithCleanup<T, S>>
.br
class FixedSizeSecBlock< T, S, A >"Fixed size stack-based \fBSecBlock\fP\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP class or type 
.br
\fIS\fP fixed-size of the stack-based memory block, in elements 
.br
\fIA\fP \fBAllocatorBase\fP derived class for allocation and cleanup 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
