.TH "FreqLessThan" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreqLessThan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (unsigned int lhs, const \fBHuffmanNode\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBHuffmanNode\fP &lhs, const \fBHuffmanNode\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBHuffmanNode\fP &lhs, unsigned int rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
