.TH "ge25519" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ge25519
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bignum25519 \fBx\fP"
.br
.ti -1c
.RI "bignum25519 \fBy\fP"
.br
.ti -1c
.RI "bignum25519 \fBz\fP"
.br
.ti -1c
.RI "bignum25519 \fBt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
