.TH "GetValueHelperClass< T, BASE >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetValueHelperClass< T, BASE >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetValueHelperClass\fP (const T *pObject, const char *name, const std::type_info &valueType, void *pValue, const \fBNameValuePairs\fP *searchFirst)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "template<class R> \fBGetValueHelperClass\fP< T, BASE > & \fBoperator()\fP (const char *name, const R &(T::*pm)() const)"
.br
.ti -1c
.RI "\fBGetValueHelperClass\fP< T, BASE > & \fBAssignable\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
