.TH "/home/mock/cryptopp-master/gf2_32.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/gf2_32.h \- Classes and functions for schemes over GF(2^32)

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGF2_32\fP"
.br
.RI "GF(2^32) with polynomial basis\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes and functions for schemes over GF(2^32)


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
