.TH "HashTestTuple" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashTestTuple
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHashTestTuple\fP (const char *input, const char *output, unsigned int repeatTimes=1)"
.br
.ti -1c
.RI "\fBHashTestTuple\fP (const char *input, unsigned int inputLen, const char *output, unsigned int repeatTimes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBbyte\fP * \fBinput\fP"
.br
.ti -1c
.RI "const \fBbyte\fP * \fBoutput\fP"
.br
.ti -1c
.RI "size_t \fBinputLen\fP"
.br
.ti -1c
.RI "size_t \fBrepeatTimes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
