.TH "HC256Info" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HC256Info \- HC-256 stream cipher information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hc256\&.h>\fP
.PP
Inherits \fBFixedKeyLength< 32, SimpleKeyingInterface::UNIQUE_IV, 32 >\fP\&.
.PP
Inherited by \fBHC256\fP, and \fBHC256Policy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char * \fBStaticAlgorithmName\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBFixedKeyLength< 32, SimpleKeyingInterface::UNIQUE_IV, 32 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (KEYLENGTH=N)"
.br
.RI "The default key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "The default key length for the algorithm provided by a static function\&. "
.in -1c
.SH "Detailed Description"
.PP 
HC-256 stream cipher information\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
