.TH "/home/mock/cryptopp-master/hex.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/hex.h \- Classes for \fBHexEncoder\fP and \fBHexDecoder\fP\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'basecode\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHexEncoder\fP"
.br
.RI "Converts given data to base 16\&. "
.ti -1c
.RI "class \fBHexDecoder\fP"
.br
.RI "Decode base 16 data back to bytes\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBHexEncoder\fP and \fBHexDecoder\fP\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
