.TH "HIGHT" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIGHT \- \fBHIGHT\fP 64-bit block cipher\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hight\&.h>\fP
.PP
Inherits \fBHIGHT_Info\fP, and \fBBlockCipherDocumentation\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.RI "\fBHIGHT\fP block cipher transformation functions\&. "
.ti -1c
.RI "class \fBDec\fP"
.br
.RI "\fBDecryption\fP transformation\&. "
.ti -1c
.RI "class \fBEnc\fP"
.br
.RI "\fBEncryption\fP transformation\&. "
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBBlockCipherFinal\fP< \fBENCRYPTION\fP, \fBEnc\fP > \fBEncryption\fP"
.br
.ti -1c
.RI "typedef \fBBlockCipherFinal\fP< \fBDECRYPTION\fP, \fBDec\fP > \fBDecryption\fP"
.br
.in -1c

Public Types inherited from \fBBlockCipherDocumentation\fP
.in +1c
.ti -1c
.RI "typedef \fBBlockCipher\fP \fBEncryption\fP"
.br
.RI "implements the \fBBlockCipher\fP interface "
.ti -1c
.RI "typedef \fBBlockCipher\fP \fBDecryption\fP"
.br
.RI "implements the \fBBlockCipher\fP interface "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBFixedBlockSize< 8 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=N)"
.br
.RI "The block size of the algorithm provided as a constant\&. "
.in -1c

Public Member Functions inherited from \fBFixedKeyLength< 16 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (KEYLENGTH=N)"
.br
.RI "The default key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "The default key length for the algorithm provided by a static function\&. "
.in -1c

Static Public Member Functions inherited from \fBHIGHT_Info\fP
.in +1c
.ti -1c
.RI "static const std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHIGHT\fP 64-bit block cipher\&. 

\fBHIGHT\fP provides 64-bit block size\&. The valid key size is 128-bits\&. 
.PP
\fBNote\fP
.RS 4
Crypto++ provides a byte oriented implementation 
.RE
.PP
\fBSee also\fP
.RS 4
\fRHIGHT\fP, \fRKorea Internet & Security Agency\fP website 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
