.TH "/home/mock/cryptopp-master/hight.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/hight.h \- Classes for the \fBHIGHT\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'algparam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHIGHT_Info\fP"
.br
.RI "\fBHIGHT\fP block cipher information\&. "
.ti -1c
.RI "class \fBHIGHT\fP"
.br
.RI "\fBHIGHT\fP 64-bit block cipher\&. "
.ti -1c
.RI "class \fBHIGHT::Base\fP"
.br
.RI "\fBHIGHT\fP block cipher transformation functions\&. "
.ti -1c
.RI "class \fBHIGHT::Enc\fP"
.br
.RI "\fBEncryption\fP transformation\&. "
.ti -1c
.RI "class \fBHIGHT::Dec\fP"
.br
.RI "\fBDecryption\fP transformation\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBHIGHT::Encryption\fP \fBHIGHTEncryption\fP"
.br
.ti -1c
.RI "typedef \fBHIGHT::Decryption\fP \fBHIGHTDecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBHIGHT\fP block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
