.TH "/home/mock/cryptopp-master/hrtimer.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/hrtimer.h \- Classes for timers\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimerBase\fP"
.br
.RI "Base class for timers\&. "
.ti -1c
.RI "class \fBThreadUserTimer\fP"
.br
.RI "Measure CPU time spent executing instructions of this thread\&. "
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "High resolution timer\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef clock_t \fBTimerWord\fP"
.br
.RI "\fBTimerWord\fP is a clock_t\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for timers\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
