.TH "HuffmanNode" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HuffmanNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHuffmanNode\fP (const \fBHuffmanNode\fP &rhs)"
.br
.ti -1c
.RI "\fBHuffmanNode\fP & \fBoperator=\fP (const \fBHuffmanNode\fP &rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsymbol\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   size_t \fBparent\fP"
.br
.ti -1c
.RI "   unsigned \fBdepth\fP"
.br
.ti -1c
.RI "   unsigned \fBfreq\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
