.TH "/home/mock/cryptopp-master/ida.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/ida.h \- Classes for \fBRabin\fP's Information Dispersal and Shamir's Secret Sharing algorithms\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'mqueue\&.h'\fP
.br
\fR#include 'filters\&.h'\fP
.br
\fR#include 'channels\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'gf2_32\&.h'\fP
.br
\fR#include 'stdcpp\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRawIDA\fP"
.br
.RI "Secret sharing and information dispersal base class\&. "
.ti -1c
.RI "class \fBSecretSharing\fP"
.br
.RI "Shamir's Secret Sharing \fBAlgorithm\fP\&. "
.ti -1c
.RI "class \fBSecretRecovery\fP"
.br
.RI "Shamir's Secret Sharing \fBAlgorithm\fP\&. "
.ti -1c
.RI "class \fBInformationDispersal\fP"
.br
.RI "a variant of \fBRabin\fP's Information Dispersal \fBAlgorithm\fP "
.ti -1c
.RI "class \fBInformationRecovery\fP"
.br
.RI "\fBRabin\fP's Information Dispersal \fBAlgorithm\fP\&. "
.ti -1c
.RI "class \fBPaddingRemover\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBRabin\fP's Information Dispersal and Shamir's Secret Sharing algorithms\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
