.TH "/home/mock/cryptopp-master/idea.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/idea.h \- Classes for the \fBIDEA\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIDEA_Info\fP"
.br
.RI "\fBIDEA\fP block cipher information\&. "
.ti -1c
.RI "class \fBIDEA\fP"
.br
.RI "\fBIDEA\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBIDEA::Encryption\fP \fBIDEAEncryption\fP"
.br
.ti -1c
.RI "typedef \fBIDEA::Decryption\fP \fBIDEADecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBIDEA\fP block cipher\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
