.TH "InitializeInteger" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitializeInteger \- Performs static initialization of the \fBInteger\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <integer\&.h>\fP
.PP
Inherited by \fBInteger\fP\fR [private]\fP\&.
.SH "Detailed Description"
.PP 
Performs static initialization of the \fBInteger\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
