.TH "IosExceptionMask" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IosExceptionMask \- Disable badbit, failbit and eof exceptions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIosExceptionMask\fP (std::istream &stream)"
.br
.ti -1c
.RI "\fBIosExceptionMask\fP (std::istream &stream, std::ios::iostate newMask)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Disable badbit, failbit and eof exceptions\&. 


.PP
\fBSee also\fP
.RS 4
https://github.com/weidai11/cryptopp/pull/968 and https://www.cplusplus.com/reference/ios/ios/exceptions 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
