.TH "/home/mock/cryptopp-master/keccak.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/keccak.h \- Classes for \fBKeccak\fP message digests\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeccak\fP"
.br
.RI "\fBKeccak\fP message digest base class\&. "
.ti -1c
.RI "class \fBKeccak_Final< T_DigestSize >\fP"
.br
.RI "\fBKeccak\fP message digest template\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBKeccak_Final\fP< 28 >, Keccak_224)"
.br
.RI "Keccak-224 message digest\&. "
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBKeccak_Final\fP< 32 >, Keccak_256)"
.br
.RI "Keccak-256 message digest\&. "
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBKeccak_Final\fP< 48 >, Keccak_384)"
.br
.RI "Keccak-384 message digest\&. "
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBKeccak_Final\fP< 64 >, Keccak_512)"
.br
.RI "Keccak-512 message digest\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBKeccak\fP message digests\&.

The Crypto++ \fBKeccak\fP implementation uses F1600 with XOF d=0x01\&. FIPS 202 conformance (XOF d=0x06) is available in \fBSHA3\fP classes\&.

.PP
\fBKeccak\fP will likely change in the future to accommodate extensibility of the round function and the XOF functions\&.
.PP
\fBSee also\fP
.RS 4
\fRKeccak\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SH "Function Documentation"
.PP
.SS "DOCUMENTED_TYPEDEF (\fBKeccak_Final\fP< 28 > , Keccak_224 )"

.PP
Keccak-224 message digest\&.
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SS "DOCUMENTED_TYPEDEF (\fBKeccak_Final\fP< 32 > , Keccak_256 )"

.PP
Keccak-256 message digest\&.
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SS "DOCUMENTED_TYPEDEF (\fBKeccak_Final\fP< 48 > , Keccak_384 )"

.PP
Keccak-384 message digest\&.
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SS "DOCUMENTED_TYPEDEF (\fBKeccak_Final\fP< 64 > , Keccak_512 )"

.PP
Keccak-512 message digest\&.
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.4
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
