.TH "/home/mock/cryptopp-master/lea.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/lea.h \- Classes for the \fBLEA\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'algparam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLEA_Info\fP"
.br
.RI "\fBLEA\fP block cipher information\&. "
.ti -1c
.RI "class \fBLEA\fP"
.br
.RI "\fBLEA\fP 128-bit block cipher\&. "
.ti -1c
.RI "class \fBLEA::Base\fP"
.br
.RI "\fBLEA\fP block cipher transformation functions\&. "
.ti -1c
.RI "class \fBLEA::Enc\fP"
.br
.RI "\fBEncryption\fP transformation\&. "
.ti -1c
.RI "class \fBLEA::Dec\fP"
.br
.RI "\fBDecryption\fP transformation\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBLEA::Encryption\fP \fBLEAEncryption\fP"
.br
.ti -1c
.RI "typedef \fBLEA::Decryption\fP \fBLEADecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBLEA\fP block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
