.TH "LowFirstBitReader" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LowFirstBitReader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <zinflate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLowFirstBitReader\fP (\fBBufferedTransformation\fP &store)"
.br
.ti -1c
.RI "unsigned int \fBBitsBuffered\fP () const"
.br
.ti -1c
.RI "unsigned long \fBPeekBuffer\fP () const"
.br
.ti -1c
.RI "bool \fBFillBuffer\fP (unsigned int length)"
.br
.ti -1c
.RI "unsigned long \fBPeekBits\fP (unsigned int length)"
.br
.ti -1c
.RI "void \fBSkipBits\fP (unsigned int length)"
.br
.ti -1c
.RI "unsigned long \fBGetBits\fP (unsigned int length)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSince\fP
.RS 4
Crypto++ 1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
