.TH "/home/mock/cryptopp-master/lsh.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/lsh.h \- Classes for the LSH hash functions\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLSH256_Base\fP"
.br
.RI "LSH-224 and LSH-256 hash base class\&. "
.ti -1c
.RI "class \fBLSH224\fP"
.br
.RI "LSH-224 hash function\&. "
.ti -1c
.RI "class \fBLSH256\fP"
.br
.RI "LSH-256 hash function\&. "
.ti -1c
.RI "class \fBLSH512_Base\fP"
.br
.RI "LSH-384 and LSH-512 hash base class\&. "
.ti -1c
.RI "class \fBLSH384\fP"
.br
.RI "LSH-384 hash function\&. "
.ti -1c
.RI "class \fBLSH512\fP"
.br
.RI "LSH-512 hash function\&. "
.ti -1c
.RI "class \fBLSH512_256\fP"
.br
.RI "LSH-512-256 hash function\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the LSH hash functions\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.6
.RE
.PP
\fBSee also\fP
.RS 4
\fRLSH\fP on the Korea Internet & Security Agency (KISA) website\&.
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
