.TH "LSH512_Internal" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSH512_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLSH512_Internal\fP (word64 *state)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lsh_u64 * \fBsubmsg_e_l\fP"
.br
.ti -1c
.RI "lsh_u64 * \fBsubmsg_e_r\fP"
.br
.ti -1c
.RI "lsh_u64 * \fBsubmsg_o_l\fP"
.br
.ti -1c
.RI "lsh_u64 * \fBsubmsg_o_r\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
