.TH "LSH512_Context" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSH512_Context
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLSH512_Context\fP (word64 *state, word64 algType, word64 &remainingBitLength)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "lsh_u64 * \fBcv_l\fP"
.br
.ti -1c
.RI "lsh_u64 * \fBcv_r\fP"
.br
.ti -1c
.RI "lsh_u64 * \fBsub_msgs\fP"
.br
.ti -1c
.RI "lsh_u8 * \fBlast_block\fP"
.br
.ti -1c
.RI "lsh_u64 & \fBremain_databitlen\fP"
.br
.ti -1c
.RI "lsh_type \fBalg_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
