.TH "LUC" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LUC \- \fBLUC\fP cryptosystem\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <luc\&.h>\fP
.PP
Inherited by \fBTF_ES< LUC, STANDARD >\fP, and \fBTF_SS< LUC, STANDARD, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBLUCFunction\fP \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBInvertibleLUCFunction\fP \fBPrivateKey\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLUC\fP cryptosystem\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
