.TH "LUCPrimeSelector" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LUCPrimeSelector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrimeSelector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLUCPrimeSelector\fP (const \fBInteger\fP &e)"
.br
.ti -1c
.RI "bool \fBIsAcceptable\fP (const \fBInteger\fP &candidate) const"
.br
.in -1c

Public Member Functions inherited from \fBPrimeSelector\fP
.in +1c
.ti -1c
.RI "const \fBPrimeSelector\fP * \fBGetSelectorPointer\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInteger\fP \fBm_e\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool LUCPrimeSelector::IsAcceptable (const \fBInteger\fP & candidate) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBPrimeSelector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
