.TH "MDC< H >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MDC< H > \- \fBMDC\fP cipher\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mdc\&.h>\fP
.PP
Inherits \fBMDC_Info< H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBBlockCipherFinal\fP< \fBENCRYPTION\fP, Enc > \fBEncryption\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBFixedBlockSize< H::DIGESTSIZE >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=N)"
.br
.RI "The block size of the algorithm provided as a constant\&. "
.in -1c

Public Member Functions inherited from \fBFixedKeyLength< H::BLOCKSIZE >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (KEYLENGTH=N)"
.br
.RI "The default key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "The default key length for the algorithm provided by a static function\&. "
.in -1c

Static Public Member Functions inherited from \fBMDC_Info< H >\fP
.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class H>
.br
class MDC< H >"\fBMDC\fP cipher\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIH\fP \fBHashTransformation\fP derived class
.RE
.PP
\fBMDC()\fP is a construction by Peter Gutmann to turn an iterated hash function into a PRF 
.PP
\fBSee also\fP
.RS 4
\fRMDC\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
