.TH "/home/mock/cryptopp-master/modarith.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/modarith.h \- Class file for performing modular arithmetic\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'integer\&.h'\fP
.br
\fR#include 'algebra\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModularArithmetic\fP"
.br
.RI "Ring of congruence classes modulo n\&. "
.ti -1c
.RI "class \fBMontgomeryRepresentation\fP"
.br
.RI "Performs modular arithmetic in Montgomery representation for increased speed\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CRYPTOPP_DLL_TEMPLATE_CLASS \fBAbstractGroup< Integer >\fP"
.br
.ti -1c
.RI "CRYPTOPP_DLL_TEMPLATE_CLASS \fBAbstractRing< Integer >\fP"
.br
.ti -1c
.RI "CRYPTOPP_DLL_TEMPLATE_CLASS \fBAbstractEuclideanDomain< Integer >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Class file for performing modular arithmetic\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
