.TH "/home/mock/cryptopp-master/mqv.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/mqv.h \- Classes for Menezes–Qu–Vanstone (\fBMQV\fP) key agreement\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'gfpcrypt\&.h'\fP
.br
\fR#include 'modarith\&.h'\fP
.br
\fR#include 'integer\&.h'\fP
.br
\fR#include 'algebra\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMQV_Domain< GROUP_PARAMETERS, COFACTOR_OPTION >\fP"
.br
.RI "\fBMQV\fP domain for performing authenticated key agreement\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBMQV_Domain\fP< \fBDL_GroupParameters_GFP_DefaultSafePrime\fP > \fBMQV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for Menezes–Qu–Vanstone (\fBMQV\fP) key agreement\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.0
.RE
.PP

.SH "Typedef Documentation"
.PP
.SS "typedef \fBMQV_Domain\fP<\fBDL_GroupParameters_GFP_DefaultSafePrime\fP> \fBMQV\fP"
Menezes-Qu-Vanstone in GF(p) with key validation, AKA \fRMQV\fP
.PP
\fBSee also\fP
.RS 4
\fBMQV\fP, \fBHMQV_Domain\fP, \fBFHMQV_Domain\fP, \fBAuthenticatedKeyAgreementDomain\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
