.TH "NewLastSmallPrimeSquared" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewLastSmallPrimeSquared
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInteger\fP * \fBoperator()\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
