.TH "NotCopyable" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotCopyable \- Ensures an object is not copyable\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <misc\&.h>\fP
.PP
Inherited by \fBFileSink\fP, \fBFileStore\fP, \fBFilter\fP, \fBHMAC_DRBG< HASH, STRENGTH, SEEDLENGTH >\fP, \fBHash_DRBG< HASH, STRENGTH, SEEDLENGTH >\fP, \fBRandomPool\fP, and \fBX917RNG\fP\&.
.SH "Detailed Description"
.PP 
Ensures an object is not copyable\&. 

\fBNotCopyable\fP ensures an object is not copyable by making the copy constructor and assignment operator private\&. Deleters are used under C++11\&. 
.PP
\fBSee also\fP
.RS 4
\fBClonable\fP class 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
