.TH "/home/mock/cryptopp-master/nr.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/nr.h \- Classes for Nyberg-Rueppel signature scheme\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'gfpcrypt\&.h'\fP
.br

.SH "Detailed Description"
.PP
Classes for Nyberg-Rueppel signature scheme\&.

Declarations for Bernstein's TweetNaCL\&.

.PP
TweetNaCL is used to cross-validate the library's implementations\&. The implementation itself is not optimized and kind of amusing\&. However it serves a valuable purpose for cross-validation\&.

.PP
Don't use this in production\&.
.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
