.TH "NULL_Hash" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NULL_Hash
.SH SYNOPSIS
.br
.PP
.PP
Inherits CryptoPP::IteratedHashWithStaticTransform< CryptoPP::word32, CryptoPP::BigEndian, 32, 0, NULL_Hash, 0 >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitState\fP (HashWordType *state)"
.br
.ti -1c
.RI "static void \fBTransform\fP (CryptoPP::word32 *digest, const CryptoPP::word32 *data)"
.br
.ti -1c
.RI "static const char * \fBStaticAlgorithmName\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
