.TH "OIDLessThan" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OIDLessThan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T> bool \fBoperator()\fP (const \fBEcRecommendedParameters\fP< T > &a, const \fBOID\fP &b)"
.br
.ti -1c
.RI "template<typename T> bool \fBoperator()\fP (const \fBOID\fP &a, const \fBEcRecommendedParameters\fP< T > &b)"
.br
.ti -1c
.RI "template<typename T> bool \fBoperator()\fP (const \fBEcRecommendedParameters\fP< T > &a, const \fBEcRecommendedParameters\fP< T > &b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
