.TH "/home/mock/cryptopp-master/osrng.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/osrng.h \- Classes for access to the operating system's random number generators\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br

.SH "Detailed Description"
.PP
Classes for access to the operating system's random number generators\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
