.TH "/home/mock/cryptopp-master/ossig.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/ossig.h \- Utility class for trapping OS signals\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br

.SH "Detailed Description"
.PP
Utility class for trapping OS signals\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.5
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
