.TH "P1363_EMSA5" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P1363_EMSA5 \- EMSA5 padding method, for use with \fBESIGN\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <esign\&.h>\fP
.PP
Inherits \fBSignatureStandard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBEMSA5Pad\fP< \fBP1363_MGF1\fP > \fBSignatureMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
EMSA5 padding method, for use with \fBESIGN\fP\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
