.TH "P1363_EMSA2" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
P1363_EMSA2 \- EMSA2/P1363 padding method\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <emsa2\&.h>\fP
.PP
Inherits \fBSignatureStandard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBEMSA2Pad\fP \fBSignatureMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
EMSA2/P1363 padding method\&. 

Use with \fBRWSS\fP and \fBRSA_ISO\fP 
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
