.TH "packedelem64_t" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packedelem64_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "word64 \fBu\fP [2]"
.br
.ti -1c
.RI "xmmi \fBv\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
