.TH "/home/mock/cryptopp-master/panama.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/panama.h \- Classes for \fBPanama\fP hash and stream cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'strciphr\&.h'\fP
.br
\fR#include 'iterhash\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPanama< B >\fP"
.br
.ti -1c
.RI "class \fBWeak::PanamaHash< B >\fP"
.br
.RI "\fBPanama\fP hash\&. "
.ti -1c
.RI "class \fBHermeticHashFunctionMAC< T_Hash, T_Info >\fP"
.br
.RI "MAC construction using a hermetic hash function\&. "
.ti -1c
.RI "class \fBWeak::PanamaMAC< B >\fP"
.br
.RI "\fBPanama\fP message authentication code\&. "
.ti -1c
.RI "struct \fBPanamaCipherInfo< B >\fP"
.br
.RI "\fBPanama\fP stream cipher information\&. "
.ti -1c
.RI "class \fBPanamaCipherPolicy< B >\fP"
.br
.RI "\fBPanama\fP stream cipher operation\&. "
.ti -1c
.RI "struct \fBPanamaCipher< B >\fP"
.br
.RI "\fBPanama\fP stream cipher\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCRYPTOPP_DISABLE_PANAMA_ASM\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBPanama\fP hash and stream cipher\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
