.TH "PasswordBasedKeyDerivationFunction" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PasswordBasedKeyDerivationFunction \- Interface for password based key derivation functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cryptlib\&.h>\fP
.PP
Inherits \fBKeyDerivationFunction\fP\&.
.PP
Inherited by \fBPKCS12_PBKDF< T >\fP, \fBPKCS5_PBKDF1< T >\fP, and \fBPKCS5_PBKDF2_HMAC< T >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBKeyDerivationFunction\fP
.in +1c
.ti -1c
.RI "virtual std::string \fBAlgorithmName\fP () const =0"
.br
.RI "Provides the name of this algorithm\&. "
.ti -1c
.RI "virtual size_t \fBMinDerivedKeyLength\fP () const"
.br
.RI "Determine minimum number of bytes\&. "
.ti -1c
.RI "virtual size_t \fBMaxDerivedKeyLength\fP () const"
.br
.RI "Determine maximum number of bytes\&. "
.ti -1c
.RI "virtual size_t \fBGetValidDerivedLength\fP (size_t keylength) const =0"
.br
.RI "Returns a valid key length for the derivation function\&. "
.ti -1c
.RI "virtual bool \fBIsValidDerivedLength\fP (size_t keylength) const"
.br
.RI "Returns whether keylength is a valid key length\&. "
.ti -1c
.RI "virtual size_t \fBDeriveKey\fP (\fBbyte\fP *derived, size_t derivedLen, const \fBbyte\fP *secret, size_t secretLen, const \fBNameValuePairs\fP &params=g_nullNameValuePairs) const =0"
.br
.RI "Derive a key from a seed\&. "
.ti -1c
.RI "virtual void \fBSetParameters\fP (const \fBNameValuePairs\fP &params)"
.br
.RI "Set or change parameters\&. "
.in -1c

Public Member Functions inherited from \fBAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (bool checkSelfTestStatus=true)"
.br
.RI "Interface for all crypto algorithms\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmProvider\fP () const"
.br
.RI "Retrieve the provider of this algorithm\&. "
.in -1c

Public Member Functions inherited from \fBClonable\fP
.in +1c
.ti -1c
.RI "virtual \fBClonable\fP * \fBClone\fP () const"
.br
.RI "Copies this object\&. "
.in -1c

Protected Member Functions inherited from \fBKeyDerivationFunction\fP
.in +1c
.ti -1c
.RI "virtual const \fBAlgorithm\fP & \fBGetAlgorithm\fP () const =0"
.br
.RI "Returns the base class \fBAlgorithm\fP\&. "
.ti -1c
.RI "void \fBThrowIfInvalidDerivedKeyLength\fP (size_t length) const"
.br
.RI "Validates the derived key length\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for password based key derivation functions\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 7\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
