.TH "PK_FinalTemplate< BASE >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PK_FinalTemplate< BASE > \- Template implementing constructors for public key algorithm classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits BASE\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPK_FinalTemplate\fP (const \fBCryptoMaterial\fP &key)"
.br
.ti -1c
.RI "\fBPK_FinalTemplate\fP (\fBBufferedTransformation\fP &bt)"
.br
.ti -1c
.RI "\fBPK_FinalTemplate\fP (const \fBAsymmetricAlgorithm\fP &algorithm)"
.br
.ti -1c
.RI "\fBPK_FinalTemplate\fP (const \fBInteger\fP &v1)"
.br
.ti -1c
.RI "template<class T1, class T2> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6, class T7> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8> \fBPK_FinalTemplate\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8)"
.br
.ti -1c
.RI "template<class T1, class T2> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6, class T7> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7)"
.br
.ti -1c
.RI "template<class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8> \fBPK_FinalTemplate\fP (T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class BASE>
.br
class PK_FinalTemplate< BASE >"Template implementing constructors for public key algorithm classes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
