.TH "PKCS_DigestDecoration< H >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PKCS_DigestDecoration< H > \- PKCS #1 decoration data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pkcspad\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBbyte\fP \fBdecoration\fP []"
.br
.ti -1c
.RI "static const unsigned int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class H>
.br
class PKCS_DigestDecoration< H >"PKCS #1 decoration data structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
