.TH "PKCS1v15" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PKCS1v15 \- PKCS #1 version 1\&.5, for use with \fBRSAES\fP and \fBRSASS\fP \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pkcspad\&.h>\fP
.PP
Inherits \fBSignatureStandard\fP, and \fBEncryptionStandard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPKCS_EncryptionPaddingScheme\fP \fBEncryptionMessageEncodingMethod\fP"
.br
.ti -1c
.RI "typedef \fBPKCS1v15_SignatureMessageEncodingMethod\fP \fBSignatureMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PKCS #1 version 1\&.5, for use with \fBRSAES\fP and \fBRSASS\fP \&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
