.TH "PolynomialOver< T >::RandomizationParameter" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PolynomialOver< T >::RandomizationParameter \- specify the distribution for randomization functions  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <polynomi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomizationParameter\fP (unsigned int coefficientCount, const typename T::RandomizationParameter &coefficientParameter)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPolynomialOver< T >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class PolynomialOver< T >::RandomizationParameter"specify the distribution for randomization functions 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
