.TH "PrivateKeyAlgorithm" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrivateKeyAlgorithm \- Interface for asymmetric algorithms using private keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cryptlib\&.h>\fP
.PP
Inherits \fBAsymmetricAlgorithm\fP\&.
.PP
Inherited by \fBPK_Decryptor\fP, and \fBPK_Signer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCryptoMaterial\fP & \fBAccessMaterial\fP ()"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "const \fBCryptoMaterial\fP & \fBGetMaterial\fP () const"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "virtual \fBPrivateKey\fP & \fBAccessPrivateKey\fP ()=0"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "virtual const \fBPrivateKey\fP & \fBGetPrivateKey\fP () const"
.br
.RI "Retrieves a reference to a Private Key\&. "
.in -1c

Public Member Functions inherited from \fBAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (bool checkSelfTestStatus=true)"
.br
.RI "Interface for all crypto algorithms\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmName\fP () const"
.br
.RI "Provides the name of this algorithm\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmProvider\fP () const"
.br
.RI "Retrieve the provider of this algorithm\&. "
.in -1c

Public Member Functions inherited from \fBClonable\fP
.in +1c
.ti -1c
.RI "virtual \fBClonable\fP * \fBClone\fP () const"
.br
.RI "Copies this object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for asymmetric algorithms using private keys\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBCryptoMaterial\fP & PrivateKeyAlgorithm::AccessMaterial ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Retrieves a reference to a Private Key\&. 
.PP
\fBReturns\fP
.RS 4
a reference the private key 
.RE
.PP

.PP
Implements \fBAsymmetricAlgorithm\fP\&.
.SS "virtual \fBPrivateKey\fP & PrivateKeyAlgorithm::AccessPrivateKey ()\fR [pure virtual]\fP"

.PP
Retrieves a reference to a Private Key\&. 
.PP
\fBReturns\fP
.RS 4
a reference the private key 
.RE
.PP

.PP
Implemented in \fBed25519Signer\fP\&.
.SS "const \fBCryptoMaterial\fP & PrivateKeyAlgorithm::GetMaterial () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Retrieves a reference to a Private Key\&. 
.PP
\fBReturns\fP
.RS 4
a const reference the private key 
.RE
.PP

.PP
Implements \fBAsymmetricAlgorithm\fP\&.
.SS "virtual const \fBPrivateKey\fP & PrivateKeyAlgorithm::GetPrivateKey () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Retrieves a reference to a Private Key\&. 
.PP
\fBReturns\fP
.RS 4
a const reference the private key 
.RE
.PP

.PP
Reimplemented in \fBed25519Signer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
