.TH "ProjectiveDoubling" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectiveDoubling
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProjectiveDoubling\fP (const \fBModularArithmetic\fP &m_mr, const \fBInteger\fP &m_a, const \fBInteger\fP &m_b, const \fBECPPoint\fP &Q)"
.br
.ti -1c
.RI "void \fBDouble\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBModularArithmetic\fP & \fBmr\fP"
.br
.ti -1c
.RI "\fBProjectivePoint\fP \fBP\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBsixteenY4\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBaZ4\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBtwoY\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBfourY2\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBS\fP"
.br
.ti -1c
.RI "\fBInteger\fP \fBM\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
