.TH "PSS" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSS \- Probabilistic Signature Scheme with Appendix\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pssr\&.h>\fP
.PP
Inherits \fBSignatureStandard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPSSR_MEM\fP< false > \fBSignatureMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Probabilistic Signature Scheme with Appendix\&. 

Signature Schemes with Appendix require the message to be provided during verification\&. 
.PP
\fBSee also\fP
.RS 4
\fRPSS-MGF1\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
