.TH "PSSR" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSSR \- Probabilistic Signature Scheme with Recovery\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pssr\&.h>\fP
.PP
Inherits \fBSignatureStandard\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPSSR_MEM\fP< true > \fBSignatureMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Probabilistic Signature Scheme with Recovery\&. 

Signature Schemes with Recovery encode the message with the signature\&. 
.PP
\fBSee also\fP
.RS 4
\fRPSSR-MGF1\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
