.TH "PSSR_MEM_BaseWithHashId< USE_HASH_ID >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSSR_MEM_BaseWithHashId< USE_HASH_ID > \- \fBPSSR\fP Message Encoding Method with Hash Identifier\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<bool USE_HASH_ID>
.br
class PSSR_MEM_BaseWithHashId< USE_HASH_ID >"\fBPSSR\fP Message Encoding Method with Hash Identifier\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIUSE_HASH_ID\fP flag indicating whether the HashId is used 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 2\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
