.TH "/home/mock/cryptopp-master/queue.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/queue.h \- Classes for an unlimited queue to store bytes\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'simple\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteQueue\fP"
.br
.RI "Data structure used to store byte strings\&. "
.ti -1c
.RI "class \fBByteQueue::Walker\fP"
.br
.RI "A \fBByteQueue\fP iterator\&. "
.ti -1c
.RI "class \fBLazyPutter\fP"
.br
.RI "Helper class to finalize Puts on \fBByteQueue\fP\&. "
.ti -1c
.RI "class \fBLazyPutterModifiable\fP"
.br
.RI "Helper class to finalize Puts on \fBByteQueue\fP\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> NAMESPACE_END void \fBswap\fP (CryptoPP::ByteQueue &a, CryptoPP::ByteQueue &b)"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for an unlimited queue to store bytes\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
