.TH "/home/mock/cryptopp-master/rabbit.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/rabbit.h \- Classes for \fBRabbit\fP stream cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'strciphr\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRabbitInfo\fP"
.br
.RI "\fBRabbit\fP stream cipher information\&. "
.ti -1c
.RI "struct \fBRabbitWithIVInfo\fP"
.br
.RI "\fBRabbit\fP stream cipher information\&. "
.ti -1c
.RI "class \fBRabbitPolicy\fP"
.br
.RI "\fBRabbit\fP stream cipher implementation\&. "
.ti -1c
.RI "class \fBRabbitWithIVPolicy\fP"
.br
.RI "\fBRabbit\fP stream cipher implementation\&. "
.ti -1c
.RI "struct \fBRabbit\fP"
.br
.RI "\fBRabbit\fP stream cipher\&. "
.ti -1c
.RI "struct \fBRabbitWithIV\fP"
.br
.RI "\fBRabbit\fP stream cipher\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBRabbit\fP stream cipher\&.


.PP
\fBSee also\fP
.RS 4
\fRThe eSTREAM Project | Rabbit\fP and \fRCrypto++ Wiki | Rabbit\fP\&.
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
