.TH "Rabin" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rabin \- \fBRabin\fP keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <rabin\&.h>\fP
.PP
Inherited by \fBTF_ES< Rabin, STANDARD >\fP, and \fBTF_SS< Rabin, STANDARD, H >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBRabinFunction\fP \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBInvertibleRabinFunction\fP \fBPrivateKey\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRabin\fP keys\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
