.TH "RabinES< STANDARD >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RabinES< STANDARD > \- \fBRabin\fP encryption scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <rabin\&.h>\fP
.PP
Inherits \fBTF_ES< Rabin, STANDARD >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBTF_ES< Rabin, STANDARD >\fP
.in +1c
.ti -1c
.RI "typedef STANDARD \fBStandard\fP"
.br
.RI "see \fBEncryptionStandard\fP for a list of standards "
.ti -1c
.RI "typedef \fBTF_CryptoSchemeOptions\fP< \fBTF_ES\fP< \fBRabin\fP, STANDARD, int >, \fBRabin\fP, MessageEncodingMethod > \fBSchemeOptions\fP"
.br
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBTF_DecryptorImpl\fP< \fBSchemeOptions\fP > > \fBDecryptor\fP"
.br
.RI "implements \fBPK_Decryptor\fP interface "
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBTF_EncryptorImpl\fP< \fBSchemeOptions\fP > > \fBEncryptor\fP"
.br
.RI "implements \fBPK_Encryptor\fP interface "
.in -1c

Public Types inherited from \fBRabin\fP
.in +1c
.ti -1c
.RI "typedef \fBRabinFunction\fP \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBInvertibleRabinFunction\fP \fBPrivateKey\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBTF_ES< Rabin, STANDARD >\fP
.in +1c
.ti -1c
.RI "static std::string CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBRabin\fP
.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class STANDARD>
.br
struct RabinES< STANDARD >"\fBRabin\fP encryption scheme\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fISTANDARD\fP encryption standard 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
