.TH "/home/mock/cryptopp-master/rc2.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/rc2.h \- Classes for the \fBRC2\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'algparam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRC2_Info\fP"
.br
.RI "\fBRC2\fP block cipher information\&. "
.ti -1c
.RI "class \fBRC2\fP"
.br
.RI "\fBRC2\fP block cipher\&. "
.ti -1c
.RI "class \fBRC2::Encryption\fP"
.br
.RI "Class specific methods used to operate the cipher in the forward direction\&. "
.ti -1c
.RI "class \fBRC2::Decryption\fP"
.br
.RI "Class specific methods used to operate the cipher in the reverse direction\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRC2::Encryption\fP \fBRC2Encryption\fP"
.br
.ti -1c
.RI "typedef \fBRC2::Decryption\fP \fBRC2Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBRC2\fP block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
