.TH "/home/mock/cryptopp-master/rc6.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/rc6.h \- Classes for the \fBRC6\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRC6_Info\fP"
.br
.RI "\fBRC6\fP block cipher information\&. "
.ti -1c
.RI "class \fBRC6\fP"
.br
.RI "\fBRC6\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRC6::Encryption\fP \fBRC6Encryption\fP"
.br
.ti -1c
.RI "typedef \fBRC6::Decryption\fP \fBRC6Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBRC6\fP block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
