.TH "/home/mock/cryptopp-master/rdrand.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/rdrand.h \- Classes for \fBRDRAND\fP and \fBRDSEED\fP\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRDRAND_Err\fP"
.br
.RI "\fBException\fP thrown when a \fBRDRAND\fP generator encounters a generator related error\&. "
.ti -1c
.RI "class \fBRDRAND\fP"
.br
.RI "Hardware generated random numbers using \fBRDRAND\fP instruction\&. "
.ti -1c
.RI "class \fBRDSEED_Err\fP"
.br
.RI "\fBException\fP thrown when a \fBRDSEED\fP generator encounters a generator related error\&. "
.ti -1c
.RI "class \fBRDSEED\fP"
.br
.RI "Hardware generated random numbers using \fBRDSEED\fP instruction\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBRDRAND\fP and \fBRDSEED\fP\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.3
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
