.TH "RegisterDefaultFactoryFor< AbstractClass, ConcreteClass, instance >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterDefaultFactoryFor< AbstractClass, ConcreteClass, instance > \- Object factory registry helper\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <factory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterDefaultFactoryFor\fP (const char *name=NULLPTR)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class AbstractClass, class ConcreteClass, int instance = 0>
.br
struct RegisterDefaultFactoryFor< AbstractClass, ConcreteClass, instance >"Object factory registry helper\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIAbstractClass\fP Base class interface of the object 
.br
\fIConcreteClass\fP Class object 
.br
\fIinstance\fP unique identifier 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
