.TH "/home/mock/cryptopp-master/rng.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/rng.h \- Miscellaneous classes for RNGs\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'filters\&.h'\fP
.br
\fR#include 'smartptr\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLC_RNG\fP"
.br
.RI "Linear Congruential Generator (LCG) "
.ti -1c
.RI "class \fBX917RNG\fP"
.br
.RI "ANSI X9\&.17 RNG\&. "
.ti -1c
.RI "class \fBMaurerRandomnessTest\fP"
.br
.RI "Maurer's Universal Statistical Test for Random Bit Generators\&. "
.in -1c
.SH "Detailed Description"
.PP
Miscellaneous classes for RNGs\&.

This file contains miscellaneous classes for RNGs, including \fBLC_RNG()\fP, \fBX917RNG()\fP and \fBMaurerRandomnessTest()\fP
.PP
\fBSee also\fP
.RS 4
\fBosrng\&.h\fP, \fBrandpool\&.h\fP
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
