.TH "RSAES< STANDARD >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RSAES< STANDARD > \- \fBRSA\fP encryption algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <rsa\&.h>\fP
.PP
Inherits \fBTF_ES< RSA, STANDARD >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBTF_ES< RSA, STANDARD >\fP
.in +1c
.ti -1c
.RI "typedef STANDARD \fBStandard\fP"
.br
.RI "see \fBEncryptionStandard\fP for a list of standards "
.ti -1c
.RI "typedef \fBTF_CryptoSchemeOptions\fP< \fBTF_ES\fP< \fBRSA\fP, STANDARD, int >, \fBRSA\fP, MessageEncodingMethod > \fBSchemeOptions\fP"
.br
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBTF_DecryptorImpl\fP< \fBSchemeOptions\fP > > \fBDecryptor\fP"
.br
.RI "implements \fBPK_Decryptor\fP interface "
.ti -1c
.RI "typedef \fBPK_FinalTemplate\fP< \fBTF_EncryptorImpl\fP< \fBSchemeOptions\fP > > \fBEncryptor\fP"
.br
.RI "implements \fBPK_Encryptor\fP interface "
.in -1c

Public Types inherited from \fBRSA\fP
.in +1c
.ti -1c
.RI "typedef \fBRSAFunction\fP \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef \fBInvertibleRSAFunction\fP \fBPrivateKey\fP"
.br
.in -1c

Public Member Functions inherited from \fBRSA\fP
.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char *CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBTF_ES< RSA, STANDARD >\fP
.in +1c
.ti -1c
.RI "static std::string CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class STANDARD>
.br
struct RSAES< STANDARD >"\fBRSA\fP encryption algorithm\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fISTANDARD\fP signature standard 
.RE
.PP
\fBSee also\fP
.RS 4
\fRRSA cryptosystem\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 1\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
