.TH "/home/mock/cryptopp-master/safer.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/safer.h \- Classes for the \fBSAFER\fP and SAFER-K block ciphers\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSAFER\fP"
.br
.RI "\fBSAFER\fP block cipher\&. "
.ti -1c
.RI "class \fBSAFER::Base\fP"
.br
.RI "\fBSAFER\fP block cipher default operation\&. "
.ti -1c
.RI "class \fBSAFER::Enc\fP"
.br
.RI "\fBSAFER\fP block cipher encryption operation\&. "
.ti -1c
.RI "class \fBSAFER::Dec\fP"
.br
.RI "\fBSAFER\fP block cipher decryption operation\&. "
.ti -1c
.RI "class \fBSAFER_Impl< BASE, INFO, STR >\fP"
.br
.RI "\fBSAFER\fP block cipher default implementation\&. "
.ti -1c
.RI "struct \fBSAFER_K_Info\fP"
.br
.RI "SAFER-K block cipher information\&. "
.ti -1c
.RI "class \fBSAFER_K\fP"
.br
.RI "SAFER-K block cipher\&. "
.ti -1c
.RI "struct \fBSAFER_SK_Info\fP"
.br
.RI "SAFER-SK block cipher information\&. "
.ti -1c
.RI "class \fBSAFER_SK\fP"
.br
.RI "SAFER-SK block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSAFER_K::Encryption\fP \fBSAFER_K_Encryption\fP"
.br
.ti -1c
.RI "typedef \fBSAFER_K::Decryption\fP \fBSAFER_K_Decryption\fP"
.br
.ti -1c
.RI "typedef \fBSAFER_SK::Encryption\fP \fBSAFER_SK_Encryption\fP"
.br
.ti -1c
.RI "typedef \fBSAFER_SK::Decryption\fP \fBSAFER_SK_Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBSAFER\fP and SAFER-K block ciphers\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
