.TH "SAFER" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAFER \- \fBSAFER\fP block cipher\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <safer\&.h>\fP
.PP
Inherited by \fBSAFER_K\fP, and \fBSAFER_SK\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.RI "\fBSAFER\fP block cipher default operation\&. "
.ti -1c
.RI "class \fBDec\fP"
.br
.RI "\fBSAFER\fP block cipher decryption operation\&. "
.ti -1c
.RI "class \fBEnc\fP"
.br
.RI "\fBSAFER\fP block cipher encryption operation\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSAFER\fP block cipher\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
