.TH "Salsa20_Info" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Salsa20_Info \- \fBSalsa20\fP stream cipher information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <salsa\&.h>\fP
.PP
Inherits \fBVariableKeyLength< 32, 16, 32, 16, SimpleKeyingInterface::UNIQUE_IV, 8 >\fP\&.
.PP
Inherited by \fBSalsa20\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBStaticAlgorithmName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBVariableKeyLength< 32, 16, 32, 16, SimpleKeyingInterface::UNIQUE_IV, 8 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (MIN_KEYLENGTH=N)"
.br
.RI "The minimum key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "Provides a valid key length for the algorithm provided by a static function\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSalsa20\fP stream cipher information\&. 


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.4 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
