.TH "Scrypt_TestTuple" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scrypt_TestTuple
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpasswd\fP"
.br
.ti -1c
.RI "const char * \fBsalt\fP"
.br
.ti -1c
.RI "word64 \fBn\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBr\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBp\fP"
.br
.ti -1c
.RI "const char * \fBexpect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
