.TH "SEAL_Gamma" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SEAL_Gamma
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSEAL_Gamma\fP (const \fBbyte\fP *key)"
.br
.ti -1c
.RI "\fBword32\fP \fBApply\fP (\fBword32\fP i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSecBlock\fP< \fBword32\fP > \fBH\fP"
.br
.ti -1c
.RI "\fBSecBlock\fP< \fBword32\fP > \fBZ\fP"
.br
.ti -1c
.RI "\fBSecBlock\fP< \fBword32\fP > \fBD\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBlastIndex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
