.TH "/home/mock/cryptopp-master/seed.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/seed.h \- Classes for the \fBSEED\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSEED_Info\fP"
.br
.RI "\fBSEED\fP block cipher information\&. "
.ti -1c
.RI "class \fBSEED\fP"
.br
.RI "\fBSEED\fP block cipher\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBSEED\fP block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
