.TH "/home/mock/cryptopp-master/serpent.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/serpent.h \- Classes for the \fBSerpent\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSerpent_Info\fP"
.br
.RI "\fBSerpent\fP block cipher information\&. "
.ti -1c
.RI "class \fBSerpent\fP"
.br
.RI "\fBSerpent\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSerpent::Encryption\fP \fBSerpentEncryption\fP"
.br
.ti -1c
.RI "typedef \fBSerpent::Decryption\fP \fBSerpentDecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBSerpent\fP block cipher\&.


.PP
\fBSee also\fP
.RS 4
\fRA Candidate Block Cipher for the Advanced Encryption Standard\fP
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
