.TH "/home/mock/cryptopp-master/sha3.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/sha3.h \- Classes for \fBSHA3\fP message digests\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSHA3\fP"
.br
.RI "\fBSHA3\fP message digest base class\&. "
.ti -1c
.RI "class \fBSHA3_Final< T_DigestSize >\fP"
.br
.RI "\fBSHA3\fP message digest template\&. "
.ti -1c
.RI "class \fBSHA3_224\fP"
.br
.RI "SHA3-224 message digest\&. "
.ti -1c
.RI "class \fBSHA3_256\fP"
.br
.RI "SHA3-256 message digest\&. "
.ti -1c
.RI "class \fBSHA3_384\fP"
.br
.RI "SHA3-384 message digest\&. "
.ti -1c
.RI "class \fBSHA3_512\fP"
.br
.RI "SHA3-512 message digest\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for \fBSHA3\fP message digests\&.

The Crypto++ implementation conforms to the FIPS 202 version of \fBSHA3\fP using F1600 with XOF d=0x06\&. Previous behavior (XOF d=0x01) is available in \fBKeccak\fP classes\&.
.PP
\fBSee also\fP
.RS 4
\fRSHA-3\fP, \fRSHA-3 STANDARD (FIPS 202)\fP\&.
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.6\&.2
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
