.TH "/home/mock/cryptopp-master/shacal2.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/shacal2.h \- Classes for the SHACAL-2 block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSHACAL2_Info\fP"
.br
.RI "\fBSHACAL2\fP block cipher information\&. "
.ti -1c
.RI "class \fBSHACAL2\fP"
.br
.RI "\fBSHACAL2\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSHACAL2::Encryption\fP \fBSHACAL2Encryption\fP"
.br
.ti -1c
.RI "typedef \fBSHACAL2::Decryption\fP \fBSHACAL2Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the SHACAL-2 block cipher\&.


.PP
\fBSince\fP
.RS 4
Crypto++ 5\&.2, Intel SHA since Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
