.TH "SignatureStandard" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignatureStandard \- Base class for public key signature standard classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherited by \fBP1363_EMSA2\fP, \fBP1363_EMSA5\fP, \fBPKCS1v15\fP, \fBPSS\fP, and \fBPSSR\fP\&.
.SH "Detailed Description"
.PP 
Base class for public key signature standard classes\&. 

These classes are used to select from variants of algorithms\&. Not all standards apply to all algorithms\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
