.TH "/home/mock/cryptopp-master/simeck.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/simeck.h \- Classes for the SIMECK block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'algparam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSIMECK32_Info\fP"
.br
.RI "SIMECK block cipher information\&. "
.ti -1c
.RI "struct \fBSIMECK64_Info\fP"
.br
.RI "SIMECK block cipher information\&. "
.ti -1c
.RI "class \fBSIMECK32\fP"
.br
.RI "SIMECK 32-bit block cipher\&. "
.ti -1c
.RI "class \fBSIMECK32::Base\fP"
.br
.RI "SIMECK block cipher transformation functions\&. "
.ti -1c
.RI "class \fBSIMECK32::Enc\fP"
.br
.RI "\fBEncryption\fP transformation\&. "
.ti -1c
.RI "class \fBSIMECK32::Dec\fP"
.br
.RI "\fBDecryption\fP transformation\&. "
.ti -1c
.RI "class \fBSIMECK64\fP"
.br
.RI "SIMECK 64-bit block cipher\&. "
.ti -1c
.RI "class \fBSIMECK64::Base\fP"
.br
.RI "SIMECK block cipher transformation functions\&. "
.ti -1c
.RI "class \fBSIMECK64::Enc\fP"
.br
.RI "\fBEncryption\fP transformation\&. "
.ti -1c
.RI "class \fBSIMECK64::Dec\fP"
.br
.RI "\fBDecryption\fP transformation\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSIMECK32::Encryption\fP \fBSIMECK32Encryption\fP"
.br
.ti -1c
.RI "typedef \fBSIMECK32::Decryption\fP \fBSIMECK32Decryption\fP"
.br
.ti -1c
.RI "typedef \fBSIMECK64::Encryption\fP \fBSIMECK64Encryption\fP"
.br
.ti -1c
.RI "typedef \fBSIMECK64::Decryption\fP \fBSIMECK64Decryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the SIMECK block cipher\&.


.PP
\fBSee also\fP
.RS 4
\fRSIMECK\fP, \fRThe Simeck Family of Lightweight Block Ciphers\fP
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 8\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
