.TH "/home/mock/cryptopp-master/simon.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/simon.h \- Classes for the Simon block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSIMON_Info< L, D, N, M >\fP"
.br
.RI "SIMON block cipher information\&. "
.ti -1c
.RI "struct \fBSIMON_Base< W >\fP"
.br
.RI "SIMON block cipher base class\&. "
.ti -1c
.RI "class \fBSIMON64\fP"
.br
.RI "SIMON 64-bit block cipher\&. "
.ti -1c
.RI "class \fBSIMON64::Base\fP"
.br
.RI "\fBSIMON64\fP block cipher base implementation\&. "
.ti -1c
.RI "class \fBSIMON64::Enc\fP"
.br
.RI "\fBSIMON64\fP encryption transformation\&. "
.ti -1c
.RI "class \fBSIMON64::Dec\fP"
.br
.RI "\fBSIMON64\fP decryption transformation\&. "
.ti -1c
.RI "class \fBSIMON128\fP"
.br
.RI "SIMON 128-bit block cipher\&. "
.ti -1c
.RI "class \fBSIMON128::Base\fP"
.br
.RI "\fBSIMON128\fP block cipher base implementation\&. "
.ti -1c
.RI "class \fBSIMON128::Enc\fP"
.br
.RI "\fBSIMON128\fP encryption transformation\&. "
.ti -1c
.RI "class \fBSIMON128::Dec\fP"
.br
.RI "\fBSIMON128\fP decryption transformation\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the Simon block cipher\&.

Simon is a block cipher designed by Ray Beaulieu, Douglas Shors, Jason Smith, Stefan Treatman-Clark, Bryan Weeks and Louis Wingers\&.
.PP
\fBSee also\fP
.RS 4
\fRThe SIMON and SPECK Families of Lightweight Block Ciphers\fP, \fRThe Simon and Speck GitHub\fP and \fRSIMON\fP on the Crypto++ wiki\&.
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
