.TH "simple_ptr< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simple_ptr< T > \- Manages resources for a single object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <smartptr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsimple_ptr\fP (T *p=NULLPTR)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBm_p\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class simple_ptr< T >"Manages resources for a single object\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP class or type
.RE
.PP
\fR\fBsimple_ptr\fP\fP is used frequently in the library to manage resources and ensure cleanup under the RAII pattern (Resource Acquisition Is Initialization)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
