.TH "/home/mock/cryptopp-master/skipjack.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/skipjack.h \- Classes for the \fBSKIPJACK\fP block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSKIPJACK_Info\fP"
.br
.RI "\fBSKIPJACK\fP block cipher information\&. "
.ti -1c
.RI "class \fBSKIPJACK\fP"
.br
.RI "\fBSKIPJACK\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSKIPJACK::Encryption\fP \fBSKIPJACKEncryption\fP"
.br
.ti -1c
.RI "typedef \fBSKIPJACK::Decryption\fP \fBSKIPJACKDecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBSKIPJACK\fP block cipher\&.

The Crypto++ implementation conforms to \fBSKIPJACK\fP and KEA \fBAlgorithm\fP Specifications published by NIST in May 1998\&. The library passes known answer tests available in NIST SP800-17, Table 6, pp\&. 140-42\&.
.PP
\fBSee also\fP
.RS 4
\fRSKIPJACK and KEA Algorithm Specifications\fP (May 1998), \fRSKIPJACK\fP on the
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
