.TH "/home/mock/cryptopp-master/sm3.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/sm3.h \- Classes for the \fBSM3\fP hash function\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'iterhash\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSM3\fP"
.br
.RI "\fBSM3\fP hash function\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBSM3\fP hash function\&.

\fBSM3\fP is a hash function designed by Xiaoyun Wang, et al\&. The hash is part of the Chinese State Cryptography Administration portfolio\&.
.PP
\fBSee also\fP
.RS 4
\fRSM3 Hash Function\fP and \fRReference implementation using OpenSSL\fP\&.
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
