.TH "/home/mock/cryptopp-master/smartptr.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/smartptr.h \- Classes for automatic resource management\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'stdcpp\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsimple_ptr< T >\fP"
.br
.RI "Manages resources for a single object\&. "
.ti -1c
.RI "class \fBmember_ptr< T >\fP"
.br
.RI "Pointer that overloads operator -> "
.ti -1c
.RI "class \fBvalue_ptr< T >\fP"
.br
.RI "Value pointer\&. "
.ti -1c
.RI "class \fBclonable_ptr< T >\fP"
.br
.RI "A pointer which can be copied and cloned\&. "
.ti -1c
.RI "class \fBcounted_ptr< T >\fP"
.br
.RI "Reference counted pointer\&. "
.ti -1c
.RI "class \fBvector_member_ptrs< T >\fP"
.br
.RI "Manages resources for an array of objects\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for automatic resource management\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
