.TH "/home/mock/cryptopp-master/speck.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/speck.h \- Classes for the Speck block cipher\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSPECK_Info< L, D, N, M >\fP"
.br
.RI "SPECK block cipher information\&. "
.ti -1c
.RI "struct \fBSPECK_Base< W >\fP"
.br
.RI "SPECK block cipher base class\&. "
.ti -1c
.RI "class \fBSPECK64\fP"
.br
.RI "SPECK 64-bit block cipher\&. "
.ti -1c
.RI "class \fBSPECK64::Base\fP"
.br
.RI "\fBSPECK64\fP block cipher base implementation\&. "
.ti -1c
.RI "class \fBSPECK64::Enc\fP"
.br
.RI "\fBSPECK64\fP encryption transformation\&. "
.ti -1c
.RI "class \fBSPECK64::Dec\fP"
.br
.RI "\fBSPECK64\fP decryption transformation\&. "
.ti -1c
.RI "class \fBSPECK128\fP"
.br
.RI "SPECK 128-bit block cipher\&. "
.ti -1c
.RI "class \fBSPECK128::Base\fP"
.br
.RI "\fBSPECK128\fP block cipher base implementation\&. "
.ti -1c
.RI "class \fBSPECK128::Enc\fP"
.br
.RI "\fBSPECK128\fP encryption transformation\&. "
.ti -1c
.RI "class \fBSPECK128::Dec\fP"
.br
.RI "\fBSPECK128\fP decryption transformation\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the Speck block cipher\&.

Speck is a block cipher designed by Ray Beaulieu, Douglas Shors, Jason Smith, Stefan Treatman-Clark, Bryan Weeks and Louis Wingers\&.
.PP
\fBSee also\fP
.RS 4
\fRThe SIMON and SPECK Families of Lightweight Block Ciphers\fP, \fRThe Simon and Speck GitHub\fP and \fRSPECK\fP on the Crypto++ wiki\&.
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 6\&.0
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
