.TH "/home/mock/cryptopp-master/tea.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/tea.h \- Classes for the \fBTEA\fP, \fBBTEA\fP and \fBXTEA\fP block ciphers\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTEA_Info\fP"
.br
.RI "\fBTEA\fP block cipher information\&. "
.ti -1c
.RI "class \fBTEA\fP"
.br
.RI "\fBTEA\fP block cipher\&. "
.ti -1c
.RI "struct \fBXTEA_Info\fP"
.br
.RI "\fBXTEA\fP block cipher information\&. "
.ti -1c
.RI "class \fBXTEA\fP"
.br
.RI "\fBXTEA\fP block cipher\&. "
.ti -1c
.RI "struct \fBBTEA_Info\fP"
.br
.RI "\fBBTEA\fP block cipher information\&. "
.ti -1c
.RI "class \fBBTEA\fP"
.br
.RI "\fBBTEA\fP block cipher\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBTEA::Encryption\fP \fBTEAEncryption\fP"
.br
.ti -1c
.RI "typedef \fBTEA::Decryption\fP \fBTEADecryption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBTEA\fP, \fBBTEA\fP and \fBXTEA\fP block ciphers\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
