.TH "TF_DecryptorBase" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TF_DecryptorBase \- Trapdoor function cryptosystems decryption base class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits \fBTF_CryptoSystemBase< PK_Decryptor, TF_Base< TrapdoorFunctionInverse, PK_EncryptionMessageEncodingMethod > >\fP\&.
.PP
Inherited by \fBAlgorithmImpl< TF_DecryptorBase, SCHEME_OPTIONS::AlgorithmInfo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecodingResult\fP \fBDecrypt\fP (\fBRandomNumberGenerator\fP &rng, const \fBbyte\fP *ciphertext, size_t ciphertextLength, \fBbyte\fP *plaintext, const \fBNameValuePairs\fP &parameters=g_nullNameValuePairs) const"
.br
.RI "Decrypt a byte string\&. "
.in -1c

Public Member Functions inherited from \fBTF_CryptoSystemBase< PK_Decryptor, TF_Base< TrapdoorFunctionInverse, PK_EncryptionMessageEncodingMethod > >\fP
.in +1c
.ti -1c
.RI "bool \fBParameterSupported\fP (const char *name) const"
.br
.ti -1c
.RI "size_t \fBFixedMaxPlaintextLength\fP () const"
.br
.ti -1c
.RI "size_t \fBFixedCiphertextLength\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBPK_FixedLengthCryptoSystemImpl< PK_Decryptor >\fP
.in +1c
.ti -1c
.RI "size_t \fBMaxPlaintextLength\fP (size_t ciphertextLength) const"
.br
.ti -1c
.RI "size_t \fBCiphertextLength\fP (size_t plaintextLength) const"
.br
.in -1c

Public Member Functions inherited from \fBPK_Decryptor\fP
.in +1c
.ti -1c
.RI "virtual \fBBufferedTransformation\fP * \fBCreateDecryptionFilter\fP (\fBRandomNumberGenerator\fP &rng, \fBBufferedTransformation\fP *attachment=NULLPTR, const \fBNameValuePairs\fP &parameters=g_nullNameValuePairs) const"
.br
.RI "Create a new decryption filter\&. "
.ti -1c
.RI "\fBDecodingResult\fP \fBFixedLengthDecrypt\fP (\fBRandomNumberGenerator\fP &rng, const \fBbyte\fP *ciphertext, \fBbyte\fP *plaintext, const \fBNameValuePairs\fP &parameters=g_nullNameValuePairs) const"
.br
.RI "Decrypt a fixed size ciphertext\&. "
.in -1c

Public Member Functions inherited from \fBPrivateKeyAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBCryptoMaterial\fP & \fBAccessMaterial\fP ()"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "const \fBCryptoMaterial\fP & \fBGetMaterial\fP () const"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "virtual \fBPrivateKey\fP & \fBAccessPrivateKey\fP ()=0"
.br
.RI "Retrieves a reference to a Private Key\&. "
.ti -1c
.RI "virtual const \fBPrivateKey\fP & \fBGetPrivateKey\fP () const"
.br
.RI "Retrieves a reference to a Private Key\&. "
.in -1c

Public Member Functions inherited from \fBAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (bool checkSelfTestStatus=true)"
.br
.RI "Interface for all crypto algorithms\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmName\fP () const"
.br
.RI "Provides the name of this algorithm\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmProvider\fP () const"
.br
.RI "Retrieve the provider of this algorithm\&. "
.in -1c

Public Member Functions inherited from \fBClonable\fP
.in +1c
.ti -1c
.RI "virtual \fBClonable\fP * \fBClone\fP () const"
.br
.RI "Copies this object\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Types inherited from \fBTF_Base< TrapdoorFunctionInverse, PK_EncryptionMessageEncodingMethod >\fP
.in +1c
.ti -1c
.RI "typedef \fBTrapdoorFunctionInverse\fP \fBTrapdoorFunctionInterface\fP"
.br
.ti -1c
.RI "typedef \fBPK_EncryptionMessageEncodingMethod\fP \fBMessageEncodingInterface\fP"
.br
.in -1c

Protected Member Functions inherited from \fBTF_CryptoSystemBase< PK_Decryptor, TF_Base< TrapdoorFunctionInverse, PK_EncryptionMessageEncodingMethod > >\fP
.in +1c
.ti -1c
.RI "size_t \fBPaddedBlockByteLength\fP () const"
.br
.ti -1c
.RI "size_t \fBPaddedBlockBitLength\fP () const"
.br
.in -1c

Protected Member Functions inherited from \fBTF_Base< TrapdoorFunctionInverse, PK_EncryptionMessageEncodingMethod >\fP
.in +1c
.ti -1c
.RI "virtual const \fBTrapdoorFunctionBounds\fP & \fBGetTrapdoorFunctionBounds\fP () const=0"
.br
.ti -1c
.RI "virtual const \fBTrapdoorFunctionInterface\fP & \fBGetTrapdoorFunctionInterface\fP () const=0"
.br
.ti -1c
.RI "virtual const \fBMessageEncodingInterface\fP & \fBGetMessageEncodingInterface\fP () const=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Trapdoor function cryptosystems decryption base class\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBDecodingResult\fP TF_DecryptorBase::Decrypt (\fBRandomNumberGenerator\fP & rng, const \fBbyte\fP * ciphertext, size_t ciphertextLength, \fBbyte\fP * plaintext, const \fBNameValuePairs\fP & parameters = \fRg_nullNameValuePairs\fP) const\fR [virtual]\fP"

.PP
Decrypt a byte string\&. 
.PP
\fBParameters\fP
.RS 4
\fIrng\fP a \fBRandomNumberGenerator\fP derived class 
.br
\fIciphertext\fP the encrypted byte buffer 
.br
\fIciphertextLength\fP the size of the encrypted byte buffer 
.br
\fIplaintext\fP a byte buffer to hold the decrypted string 
.br
\fIparameters\fP a set of \fBNameValuePairs\fP to initialize this object 
.RE
.PP
\fBReturns\fP
.RS 4
the result of the decryption operation
.RE
.PP
If \fBDecodingResult::isValidCoding\fP is true, then \fBDecodingResult::messageLength\fP is valid and holds the actual length of the plaintext recovered\&. The result is undefined if decryption failed\&. If \fBDecodingResult::isValidCoding\fP is false, then \fBDecodingResult::messageLength\fP is undefined\&. 
.PP
\fBPrecondition\fP
.RS 4
\fRCOUNTOF(plaintext) == MaxPlaintextLength(ciphertextLength)\fP ensures the output byte buffer is large enough 
.RE
.PP
\fBSee also\fP
.RS 4
\fBPK_Encryptor\fP 
.RE
.PP

.PP
Implements \fBPK_Decryptor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
