.TH "TF_SignatureSchemeOptions< T1, T2, T3, T4 >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TF_SignatureSchemeOptions< T1, T2, T3, T4 > \- Trapdoor Function (TF) signature scheme options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits \fBTF_CryptoSchemeOptions< T1, T2, T3 >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T4 \fBHashFunction\fP"
.br
.in -1c

Public Types inherited from \fBTF_CryptoSchemeOptions< T1, T2, T3 >\fP
.in +1c
.ti -1c
.RI "typedef T1 \fBAlgorithmInfo\fP"
.br
.ti -1c
.RI "typedef T2 \fBKeys\fP"
.br
.ti -1c
.RI "typedef Keys::PrivateKey \fBPrivateKey\fP"
.br
.ti -1c
.RI "typedef Keys::PublicKey \fBPublicKey\fP"
.br
.ti -1c
.RI "typedef T3 \fBMessageEncodingMethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T1, class T2, class T3, class T4>
.br
struct TF_SignatureSchemeOptions< T1, T2, T3, T4 >"Trapdoor Function (TF) signature scheme options\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT1\fP algorithm info class 
.br
\fIT2\fP keys class with public and private key 
.br
\fIT3\fP message encoding class 
.br
\fIT4\fP \fBHashTransformation\fP class 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
