.TH "TF_VerifierImpl< SCHEME_OPTIONS >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TF_VerifierImpl< SCHEME_OPTIONS > \- Trapdoor Function (TF) encryptor options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pubkey\&.h>\fP
.PP
Inherits \fBTF_ObjectImpl< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP\&.
.PP
Inherited by \fBPK_FinalTemplate< TF_VerifierImpl< SchemeOptions > >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBTF_ObjectImpl< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP
.in +1c
.ti -1c
.RI "typedef SCHEME_OPTIONS::PublicKey \fBKeyClass\fP"
.br
.in -1c

Public Types inherited from \fBTF_ObjectImplBase< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP
.in +1c
.ti -1c
.RI "typedef SCHEME_OPTIONS \fBSchemeOptions\fP"
.br
.ti -1c
.RI "typedef SCHEME_OPTIONS::PublicKey \fBKeyClass\fP"
.br
.in -1c

Public Member Functions inherited from \fBTF_ObjectImpl< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP
.in +1c
.ti -1c
.RI "const KeyClass & \fBGetKey\fP () const"
.br
.ti -1c
.RI "KeyClass & \fBAccessKey\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTF_ObjectImplBase< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP
.in +1c
.ti -1c
.RI "\fBPublicKey\fP & \fBAccessPublicKey\fP ()"
.br
.ti -1c
.RI "const \fBPublicKey\fP & \fBGetPublicKey\fP () const"
.br
.ti -1c
.RI "\fBPrivateKey\fP & \fBAccessPrivateKey\fP ()"
.br
.ti -1c
.RI "const \fBPrivateKey\fP & \fBGetPrivateKey\fP () const"
.br
.ti -1c
.RI "const KeyClass & \fBGetTrapdoorFunction\fP () const"
.br
.ti -1c
.RI "\fBPK_MessageAccumulator\fP * \fBNewSignatureAccumulator\fP (\fBRandomNumberGenerator\fP &rng) const"
.br
.ti -1c
.RI "\fBPK_MessageAccumulator\fP * \fBNewVerificationAccumulator\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBAlgorithmImpl< TF_VerifierBase, SCHEME_OPTIONS::AlgorithmInfo >\fP
.in +1c
.ti -1c
.RI "std::string \fBAlgorithmName\fP () const"
.br
.RI "The algorithm name\&. "
.in -1c

Public Member Functions inherited from \fBTF_VerifierBase\fP
.in +1c
.ti -1c
.RI "void \fBInputSignature\fP (\fBPK_MessageAccumulator\fP &messageAccumulator, const \fBbyte\fP *signature, size_t signatureLength) const"
.br
.RI "Input signature into a message accumulator\&. "
.ti -1c
.RI "bool \fBVerifyAndRestart\fP (\fBPK_MessageAccumulator\fP &messageAccumulator) const"
.br
.RI "Check whether messageAccumulator contains a valid signature and message, and restart messageAccumulator\&. "
.ti -1c
.RI "\fBDecodingResult\fP \fBRecoverAndRestart\fP (\fBbyte\fP *recoveredMessage, \fBPK_MessageAccumulator\fP &recoveryAccumulator) const"
.br
.RI "Recover a message from its signature\&. "
.in -1c

Public Member Functions inherited from \fBTF_SignatureSchemeBase< PK_Verifier, TF_Base< TrapdoorFunction, PK_SignatureMessageEncodingMethod > >\fP
.in +1c
.ti -1c
.RI "size_t \fBSignatureLength\fP () const"
.br
.ti -1c
.RI "size_t \fBMaxRecoverableLength\fP () const"
.br
.ti -1c
.RI "size_t \fBMaxRecoverableLengthFromSignatureLength\fP (size_t signatureLength) const"
.br
.ti -1c
.RI "bool \fBIsProbabilistic\fP () const"
.br
.ti -1c
.RI "bool \fBAllowNonrecoverablePart\fP () const"
.br
.ti -1c
.RI "bool \fBRecoverablePartFirst\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBPK_Verifier\fP
.in +1c
.ti -1c
.RI "virtual bool \fBVerify\fP (\fBPK_MessageAccumulator\fP *messageAccumulator) const"
.br
.RI "Check whether messageAccumulator contains a valid signature and message\&. "
.ti -1c
.RI "virtual bool \fBVerifyMessage\fP (const \fBbyte\fP *message, size_t messageLen, const \fBbyte\fP *signature, size_t signatureLen) const"
.br
.RI "Check whether input signature is a valid signature for input message\&. "
.ti -1c
.RI "virtual \fBDecodingResult\fP \fBRecover\fP (\fBbyte\fP *recoveredMessage, \fBPK_MessageAccumulator\fP *messageAccumulator) const"
.br
.RI "Recover a message from its signature\&. "
.ti -1c
.RI "virtual \fBDecodingResult\fP \fBRecoverMessage\fP (\fBbyte\fP *recoveredMessage, const \fBbyte\fP *nonrecoverableMessage, size_t nonrecoverableMessageLength, const \fBbyte\fP *signature, size_t signatureLength) const"
.br
.RI "Recover a message from its signature\&. "
.in -1c

Public Member Functions inherited from \fBPK_SignatureScheme\fP
.in +1c
.ti -1c
.RI "virtual size_t \fBMaxSignatureLength\fP (size_t recoverablePartLength=0) const"
.br
.RI "Provides the maximum signature length produced given the length of the recoverable message part\&. "
.ti -1c
.RI "virtual bool \fBSignatureUpfront\fP () const"
.br
.RI "Determines whether the signature must be input before the message\&. "
.in -1c

Public Member Functions inherited from \fBPublicKeyAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBCryptoMaterial\fP & \fBAccessMaterial\fP ()"
.br
.RI "Retrieves a reference to a Public Key\&. "
.ti -1c
.RI "const \fBCryptoMaterial\fP & \fBGetMaterial\fP () const"
.br
.RI "Retrieves a reference to a Public Key\&. "
.in -1c

Public Member Functions inherited from \fBAlgorithm\fP
.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (bool checkSelfTestStatus=true)"
.br
.RI "Interface for all crypto algorithms\&. "
.ti -1c
.RI "virtual std::string \fBAlgorithmProvider\fP () const"
.br
.RI "Retrieve the provider of this algorithm\&. "
.in -1c

Public Member Functions inherited from \fBClonable\fP
.in +1c
.ti -1c
.RI "virtual \fBClonable\fP * \fBClone\fP () const"
.br
.RI "Copies this object\&. "
.in -1c

Static Public Member Functions inherited from \fBAlgorithmImpl< TF_VerifierBase, SCHEME_OPTIONS::AlgorithmInfo >\fP
.in +1c
.ti -1c
.RI "static std::string CRYPTOPP_API \fBStaticAlgorithmName\fP ()"
.br
.RI "The algorithm name\&. "
.in -1c

Protected Types inherited from \fBTF_Base< TrapdoorFunction, PK_SignatureMessageEncodingMethod >\fP
.in +1c
.ti -1c
.RI "typedef \fBTrapdoorFunction\fP \fBTrapdoorFunctionInterface\fP"
.br
.ti -1c
.RI "typedef \fBPK_SignatureMessageEncodingMethod\fP \fBMessageEncodingInterface\fP"
.br
.in -1c

Protected Member Functions inherited from \fBTF_ObjectImplBase< TF_VerifierBase, SCHEME_OPTIONS, SCHEME_OPTIONS::PublicKey >\fP
.in +1c
.ti -1c
.RI "const \fBTF_VerifierBase::MessageEncodingInterface\fP & \fBGetMessageEncodingInterface\fP () const"
.br
.ti -1c
.RI "const \fBTrapdoorFunctionBounds\fP & \fBGetTrapdoorFunctionBounds\fP () const"
.br
.ti -1c
.RI "const \fBTF_VerifierBase::TrapdoorFunctionInterface\fP & \fBGetTrapdoorFunctionInterface\fP () const"
.br
.ti -1c
.RI "HashIdentifier \fBGetHashIdentifier\fP () const"
.br
.ti -1c
.RI "size_t \fBGetDigestSize\fP () const"
.br
.in -1c

Protected Member Functions inherited from \fBTF_SignatureSchemeBase< PK_Verifier, TF_Base< TrapdoorFunction, PK_SignatureMessageEncodingMethod > >\fP
.in +1c
.ti -1c
.RI "size_t \fBMessageRepresentativeLength\fP () const"
.br
.ti -1c
.RI "size_t \fBMessageRepresentativeBitLength\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SCHEME_OPTIONS>
.br
class TF_VerifierImpl< SCHEME_OPTIONS >"Trapdoor Function (TF) encryptor options\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fISCHEME_OPTIONS\fP scheme options class 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
