.TH "/home/mock/cryptopp-master/trunhash.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/trunhash.h \- Classes for truncated hashes\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNullHash\fP"
.br
.RI "Null hash\&. "
.ti -1c
.RI "class \fBTruncatedHashTemplate< T >\fP"
.br
.RI "Construct new HashModule with smaller digest size from an existing one\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBTruncatedHashTemplate\fP< \fBHashTransformation\fP & > \fBTruncatedHashModule\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
Classes for truncated hashes\&.


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
