.TH "/home/mock/cryptopp-master/ttmac.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/ttmac.h \- Classes for the TTMAC message authentication code\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'seckey\&.h'\fP
.br
\fR#include 'iterhash\&.h'\fP
.br
\fR#include 'secblock\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTTMAC_Base\fP"
.br
.RI "TTMAC message authentication code information\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDOCUMENTED_TYPEDEF\fP (\fBMessageAuthenticationCodeFinal\fP< \fBTTMAC_Base\fP >, TTMAC)"
.br
.RI "Two-Track-MAC message authentication code\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the TTMAC message authentication code\&.


.SH "Function Documentation"
.PP
.SS "DOCUMENTED_TYPEDEF (\fBMessageAuthenticationCodeFinal\fP< \fBTTMAC_Base\fP > , TTMAC )"

.PP
Two-Track-MAC message authentication code\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP \fBHashTransformation\fP class
.RE
.PP
160-bit MAC with 160-bit key
.PP
\fBSee also\fP
.RS 4
\fBMessageAuthenticationCode()\fP, \fRTwo-Track-MAC\fP
.RE
.PP

.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
