.TH "Twofish" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Twofish \- \fBTwofish\fP block cipher\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <twofish\&.h>\fP
.PP
Inherits \fBTwofish_Info\fP, and \fBBlockCipherDocumentation\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBBlockCipherFinal\fP< \fBENCRYPTION\fP, Enc > \fBEncryption\fP"
.br
.ti -1c
.RI "typedef \fBBlockCipherFinal\fP< \fBDECRYPTION\fP, Dec > \fBDecryption\fP"
.br
.in -1c

Public Types inherited from \fBBlockCipherDocumentation\fP
.in +1c
.ti -1c
.RI "typedef \fBBlockCipher\fP \fBEncryption\fP"
.br
.RI "implements the \fBBlockCipher\fP interface "
.ti -1c
.RI "typedef \fBBlockCipher\fP \fBDecryption\fP"
.br
.RI "implements the \fBBlockCipher\fP interface "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBTwofish_Info\fP
.in +1c
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR const char * \fBStaticAlgorithmName\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBFixedBlockSize< 16 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (BLOCKSIZE=N)"
.br
.RI "The block size of the algorithm provided as a constant\&. "
.in -1c

Public Member Functions inherited from \fBVariableKeyLength< 16, 16, 32, 8 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (MIN_KEYLENGTH=N)"
.br
.RI "The minimum key length used by the algorithm provided as a constant\&. "
.ti -1c
.RI "CRYPTOPP_STATIC_CONSTEXPR size_t CRYPTOPP_API \fBStaticGetValidKeyLength\fP (size_t keylength)"
.br
.RI "Provides a valid key length for the algorithm provided by a static function\&. "
.in -1c

Public Member Functions inherited from \fBFixedRounds< 16 >\fP
.in +1c
.ti -1c
.RI "\fBCRYPTOPP_CONSTANT\fP (ROUNDS=R)"
.br
.RI "The number of rounds for the algorithm provided as a constant\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTwofish\fP block cipher\&. 


.PP
\fBSee also\fP
.RS 4
\fRTwofish\fP 
.RE
.PP
\fBSince\fP
.RS 4
Crypto++ 3\&.1 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
