.TH "WAKE_Base" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAKE_Base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBWAKE_Policy< B >\fP\fR [protected]\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBword32\fP \fBM\fP (\fBword32\fP x, \fBword32\fP y)"
.br
.ti -1c
.RI "void \fBGenKey\fP (\fBword32\fP k0, \fBword32\fP k1, \fBword32\fP k2, \fBword32\fP k3)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBword32\fP \fBt\fP [257]"
.br
.ti -1c
.RI "\fBword32\fP \fBr3\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBr4\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBr5\fP"
.br
.ti -1c
.RI "\fBword32\fP \fBr6\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
