.TH "/home/mock/cryptopp-master/whrlpool.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/whrlpool.h \- Classes for the \fBWhirlpool\fP message digest\&.

.SH SYNOPSIS
.br
.PP
\fR#include 'config\&.h'\fP
.br
\fR#include 'iterhash\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWhirlpool\fP"
.br
.RI "\fBWhirlpool\fP message digest\&. "
.in -1c
.SH "Detailed Description"
.PP
Classes for the \fBWhirlpool\fP message digest\&.

Crypto++ provides version 3\&.0 of the \fBWhirlpool\fP algorithm\&. This version of the algorithm was submitted for ISO standardization\&.
.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
