.TH "Word" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Word
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWord\fP (word value)"
.br
.ti -1c
.RI "\fBWord\fP (hword low, hword high)"
.br
.ti -1c
.RI "\fBWord\fP \fBoperator\-\fP (\fBWord\fP a)"
.br
.ti -1c
.RI "\fBWord\fP \fBoperator\-\fP (hword a)"
.br
.ti -1c
.RI "hword \fBoperator/\fP (hword divisor)"
.br
.ti -1c
.RI "bool \fBoperator!\fP () const"
.br
.ti -1c
.RI "word \fBGetWhole\fP () const"
.br
.ti -1c
.RI "hword \fBGetLowHalf\fP () const"
.br
.ti -1c
.RI "hword \fBGetHighHalf\fP () const"
.br
.ti -1c
.RI "hword \fBGetHighHalfAsBorrow\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBWord\fP \fBMultiply\fP (hword a, hword b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
