.TH "/home/mock/cryptopp-master/zdeflate.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mock/cryptopp-master/zdeflate.h \- DEFLATE compression and decompression (RFC 1951)

.SH SYNOPSIS
.br
.PP
\fR#include 'cryptlib\&.h'\fP
.br
\fR#include 'filters\&.h'\fP
.br
\fR#include 'misc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLowFirstBitWriter\fP"
.br
.RI "Encoding table writer\&. "
.ti -1c
.RI "class \fBHuffmanEncoder\fP"
.br
.RI "Huffman Encoder\&. "
.ti -1c
.RI "struct \fBHuffmanEncoder::Code\fP"
.br
.ti -1c
.RI "class \fBDeflator\fP"
.br
.RI "DEFLATE compressor (RFC 1951) "
.ti -1c
.RI "struct \fBDeflator::EncodedMatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP
DEFLATE compression and decompression (RFC 1951)


.SH "Author"
.PP
Generated automatically by Doxygen for My Project from the source code\&.
