.TH "ZIterator" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZIterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZIterator\fP (std::vector< \fBProjectivePoint\fP >::iterator it)"
.br
.ti -1c
.RI "\fBInteger\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "int \fBoperator\-\fP (\fBZIterator\fP it2)"
.br
.ti -1c
.RI "\fBZIterator\fP \fBoperator+\fP (int i)"
.br
.ti -1c
.RI "\fBZIterator\fP & \fBoperator+=\fP (int i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBProjectivePoint\fP >::iterator \fBit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
