.TH "agent_callback_state" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
agent_callback_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcalled\fP"
.br
.ti -1c
.RI "\fBssh_session\fP \fBexpected_session\fP"
.br
.ti -1c
.RI "\fBssh_channel\fP \fBcreated_channel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
