.TH "arguments_st" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arguments_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum ssh_keytypes_e \fBtype\fP"
.br
.ti -1c
.RI "unsigned long \fBbits\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "char * \fBpassphrase\fP"
.br
.ti -1c
.RI "char * \fBformat\fP"
.br
.ti -1c
.RI "int \fBaction_list\fP"
.br
.ti -1c
.RI "char * \fBaddress\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.ti -1c
.RI "char * \fBecdsa_key\fP"
.br
.ti -1c
.RI "char * \fBed25519_key\fP"
.br
.ti -1c
.RI "char * \fBrsa_key\fP"
.br
.ti -1c
.RI "char * \fBhost_key\fP"
.br
.ti -1c
.RI "char * \fBverbosity\fP"
.br
.ti -1c
.RI "char * \fBauth_methods\fP"
.br
.ti -1c
.RI "bool \fBwith_pcap\fP"
.br
.ti -1c
.RI "char * \fBpcap_file\fP"
.br
.ti -1c
.RI "char * \fBusername\fP"
.br
.ti -1c
.RI "char * \fBpassword\fP"
.br
.ti -1c
.RI "char * \fBconfig_file\fP"
.br
.ti -1c
.RI "char * \fBlog_file\fP"
.br
.ti -1c
.RI "bool \fBwith_global_config\fP"
.br
.ti -1c
.RI "char * \fBpid_file\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
