.TH "bind_st" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bind_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcwd\fP"
.br
.ti -1c
.RI "char * \fBtemp_dir\fP"
.br
.ti -1c
.RI "\fBssh_bind\fP \fBbind\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
