.TH "bug" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP


.PP
.IP "\fBMember \fBssh_threads_set_callbacks\fP (struct \fBssh_threads_callbacks_struct\fP *cb)
.IP "" 1c
libgcrypt 1\&.6 and bigger backend does not support custom callback\&. Using anything else than pthreads here will fail\&. 

.PP

