.TH "chacha20_poly1305_keysched" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chacha20_poly1305_keysched
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBchacha_ctx\fP \fBk1\fP"
.br
.ti -1c
.RI "struct \fBchacha_ctx\fP \fBk2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
