.TH "channel_data" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
channel_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBshould_accept\fP"
.br
.ti -1c
.RI "int \fBreq_seen\fP"
.br
.ti -1c
.RI "char * \fBdest_host\fP"
.br
.ti -1c
.RI "uint32_t \fBdest_port\fP"
.br
.ti -1c
.RI "char * \fBorig_host\fP"
.br
.ti -1c
.RI "uint32_t \fBorig_port\fP"
.br
.ti -1c
.RI "uint32_t \fBscreen_number\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
