.TH "channel_data_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
channel_data_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_event\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBsftp_session\fP \fBsftp\fP"
.br
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "socket_t \fBpty_master\fP"
.br
.ti -1c
.RI "socket_t \fBpty_slave\fP"
.br
.ti -1c
.RI "socket_t \fBchild_stdin\fP"
.br
.ti -1c
.RI "socket_t \fBchild_stdout\fP"
.br
.ti -1c
.RI "socket_t \fBchild_stderr\fP"
.br
.ti -1c
.RI "struct winsize * \fBwinsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
