.TH "global_state_st" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global_state_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint8_t \fBrole\fP"
.br
.ti -1c
.RI "enum ssh_session_state_e \fBsession\fP"
.br
.ti -1c
.RI "enum ssh_dh_state_e \fBdh\fP"
.br
.ti -1c
.RI "enum ssh_auth_state_e \fBauth\fP"
.br
.ti -1c
.RI "enum ssh_channel_request_state_e \fBglobal_req\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
