.TH "hostkey_state" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hostkey_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBhostkey\fP"
.br
.ti -1c
.RI "char * \fBhostkey_path\fP"
.br
.ti -1c
.RI "enum ssh_keytypes_e \fBkey_type\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
