.TH "key_attrs" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
key_attrs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "int \fBverify\fP"
.br
.ti -1c
.RI "const char * \fBtype_c\fP"
.br
.ti -1c
.RI "int \fBsize_arg\fP"
.br
.ti -1c
.RI "int \fBsig_length\fP"
.br
.ti -1c
.RI "const char * \fBsig_type_c\fP"
.br
.ti -1c
.RI "int \fBexpect_success\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
