.TH "server_thread_args" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server_thread_args
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBhostkey_state\fP * \fBh\fP"
.br
.ti -1c
.RI "bool \fBshould_accept\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
