.TH "sftp_file_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sftp_file_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsftp_session\fP \fBsftp\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "uint64_t \fBoffset\fP"
.br
.ti -1c
.RI "\fBssh_string\fP \fBhandle\fP"
.br
.ti -1c
.RI "int \fBeof\fP"
.br
.ti -1c
.RI "int \fBnonblocking\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
