.TH "sftp_handle" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sftp_handle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum sftp_handle_type \fBtype\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "DIR * \fBdirp\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
