.TH "sftp_session_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sftp_session_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_session\fP \fBsession\fP"
.br
.ti -1c
.RI "\fBssh_channel\fP \fBchannel\fP"
.br
.ti -1c
.RI "int \fBserver_version\fP"
.br
.ti -1c
.RI "int \fBclient_version\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "\fBsftp_request_queue\fP \fBqueue\fP"
.br
.ti -1c
.RI "uint32_t \fBid_counter\fP"
.br
.ti -1c
.RI "int \fBerrnum\fP"
.br
.ti -1c
.RI "void ** \fBhandles\fP"
.br
.ti -1c
.RI "sftp_ext \fBext\fP"
.br
.ti -1c
.RI "\fBsftp_packet\fP \fBread_packet\fP"
.br
.ti -1c
.RI "\fBsftp_limits_t\fP \fBlimits\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
