.TH "sftp_client_message_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sftp_client_message_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsftp_session\fP \fBsftp\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "\fBsftp_attributes\fP \fBattr\fP"
.br
.ti -1c
.RI "\fBssh_string\fP \fBhandle\fP"
.br
.ti -1c
.RI "uint64_t \fBoffset\fP"
.br
.ti -1c
.RI "uint32_t \fBlen\fP"
.br
.ti -1c
.RI "int \fBattr_num\fP"
.br
.ti -1c
.RI "\fBssh_buffer\fP \fBattrbuf\fP"
.br
.ti -1c
.RI "\fBssh_string\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBssh_buffer\fP \fBcomplete_message\fP"
.br
.ti -1c
.RI "char * \fBstr_data\fP"
.br
.ti -1c
.RI "char * \fBsubmessage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
