.TH "ssh_buffer_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_buffer_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsecure\fP"
.br
.ti -1c
.RI "uint32_t \fBused\fP"
.br
.ti -1c
.RI "uint32_t \fBallocated\fP"
.br
.ti -1c
.RI "uint32_t \fBpos\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
