.TH "ssh_poll_ctx_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_poll_ctx_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_poll_handle\fP * \fBpollptrs\fP"
.br
.ti -1c
.RI "\fBssh_pollfd_t\fP * \fBpollfds\fP"
.br
.ti -1c
.RI "size_t \fBpolls_allocated\fP"
.br
.ti -1c
.RI "size_t \fBpolls_used\fP"
.br
.ti -1c
.RI "size_t \fBchunk_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
