.TH "ssh_pollfd_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_pollfd_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "socket_t \fBfd\fP"
.br
.ti -1c
.RI "short \fBevents\fP"
.br
.ti -1c
.RI "short \fBrevents\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
