.TH "ssh_event_fd_wrapper" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_event_fd_wrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ssh_event_callback \fBcb\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
