.TH "ssh_channel_request_open" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_channel_request_open
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBsender\fP"
.br
.ti -1c
.RI "uint32_t \fBwindow\fP"
.br
.ti -1c
.RI "uint32_t \fBpacket_size\fP"
.br
.ti -1c
.RI "char * \fBoriginator\fP"
.br
.ti -1c
.RI "uint16_t \fBoriginator_port\fP"
.br
.ti -1c
.RI "char * \fBdestination\fP"
.br
.ti -1c
.RI "uint16_t \fBdestination_port\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
