.TH "ssh_hmac_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_hmac_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "enum ssh_hmac_e \fBhmac_type\fP"
.br
.ti -1c
.RI "bool \fBetm\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
