.TH "ssh_threads_callbacks_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_threads_callbacks_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtype\fP"
.br
.ti -1c
.RI "ssh_thread_callback \fBmutex_init\fP"
.br
.ti -1c
.RI "ssh_thread_callback \fBmutex_destroy\fP"
.br
.ti -1c
.RI "ssh_thread_callback \fBmutex_lock\fP"
.br
.ti -1c
.RI "ssh_thread_callback \fBmutex_unlock\fP"
.br
.ti -1c
.RI "ssh_thread_id_callback \fBthread_id\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
