.TH "ssh_channel_request" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_channel_request
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBssh_channel\fP \fBchannel\fP"
.br
.ti -1c
.RI "uint8_t \fBwant_reply\fP"
.br
.ti -1c
.RI "char * \fBTERM\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint32_t \fBpxwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBpxheight\fP"
.br
.ti -1c
.RI "\fBssh_string\fP \fBmodes\fP"
.br
.ti -1c
.RI "char * \fBvar_name\fP"
.br
.ti -1c
.RI "char * \fBvar_value\fP"
.br
.ti -1c
.RI "char * \fBcommand\fP"
.br
.ti -1c
.RI "char * \fBsubsystem\fP"
.br
.ti -1c
.RI "uint8_t \fBx11_single_connection\fP"
.br
.ti -1c
.RI "char * \fBx11_auth_protocol\fP"
.br
.ti -1c
.RI "char * \fBx11_auth_cookie\fP"
.br
.ti -1c
.RI "uint32_t \fBx11_screen_number\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
