.TH "ssh_string_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_string_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
