.TH "ssh_config_match_keyword_table_s" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_config_match_keyword_table_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "enum ssh_config_match_e \fBopcode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
