.TH "ssh_auth_request" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_auth_request
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBusername\fP"
.br
.ti -1c
.RI "int \fBmethod\fP"
.br
.ti -1c
.RI "char * \fBpassword\fP"
.br
.ti -1c
.RI "struct \fBssh_key_struct\fP * \fBpubkey\fP"
.br
.ti -1c
.RI "struct \fBssh_key_struct\fP * \fBserver_pubkey\fP"
.br
.ti -1c
.RI "char * \fBsigtype\fP"
.br
.ti -1c
.RI "enum ssh_publickey_state_e \fBsignature_state\fP"
.br
.ti -1c
.RI "char \fBkbdint_response\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
