.TH "ssh_message_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_message_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_session\fP \fBsession\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "struct \fBssh_auth_request\fP \fBauth_request\fP"
.br
.ti -1c
.RI "struct \fBssh_channel_request_open\fP \fBchannel_request_open\fP"
.br
.ti -1c
.RI "struct \fBssh_channel_request\fP \fBchannel_request\fP"
.br
.ti -1c
.RI "struct \fBssh_service_request\fP \fBservice_request\fP"
.br
.ti -1c
.RI "struct \fBssh_global_request\fP \fBglobal_request\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
