.TH "ssh_scp_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_scp_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_session\fP \fBsession\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBrecursive\fP"
.br
.ti -1c
.RI "\fBssh_channel\fP \fBchannel\fP"
.br
.ti -1c
.RI "char * \fBlocation\fP"
.br
.ti -1c
.RI "enum ssh_scp_states \fBstate\fP"
.br
.ti -1c
.RI "uint64_t \fBfilelen\fP"
.br
.ti -1c
.RI "uint64_t \fBprocessed\fP"
.br
.ti -1c
.RI "enum ssh_scp_request_types \fBrequest_type\fP"
.br
.ti -1c
.RI "char * \fBrequest_name\fP"
.br
.ti -1c
.RI "char * \fBwarning\fP"
.br
.ti -1c
.RI "int \fBrequest_mode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
