.TH "ssh_kbdint_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_kbdint_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnprompts\fP"
.br
.ti -1c
.RI "uint32_t \fBnanswers\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBinstruction\fP"
.br
.ti -1c
.RI "char ** \fBprompts\fP"
.br
.ti -1c
.RI "unsigned char * \fBecho\fP"
.br
.ti -1c
.RI "char ** \fBanswers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
