.TH "ssh_agent_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_agent_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBssh_socket_struct\fP * \fBsock\fP"
.br
.ti -1c
.RI "\fBssh_buffer\fP \fBident\fP"
.br
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.ti -1c
.RI "\fBssh_channel\fP \fBchannel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
