.TH "ssh_jump_callbacks_struct" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssh_jump_callbacks_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "ssh_jump_before_connection_callback \fBbefore_connection\fP"
.br
.ti -1c
.RI "ssh_jump_verify_knownhost_callback \fBverify_knownhost\fP"
.br
.ti -1c
.RI "ssh_jump_authenticate_callback \fBauthenticate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
