.TH "sshsig_st" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sshsig_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBoriginal_cwd\fP"
.br
.ti -1c
.RI "char * \fBtemp_dir\fP"
.br
.ti -1c
.RI "\fBssh_key\fP \fBrsa_key\fP"
.br
.ti -1c
.RI "\fBssh_key\fP \fBed25519_key\fP"
.br
.ti -1c
.RI "\fBssh_key\fP \fBecdsa_key\fP"
.br
.ti -1c
.RI "const char * \fBssh_keygen_path\fP"
.br
.ti -1c
.RI "const struct \fBkey_hash_combo\fP * \fBtest_combinations\fP"
.br
.ti -1c
.RI "size_t \fBnum_combinations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
