.TH "test_st" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBtemp_dir\fP"
.br
.ti -1c
.RI "char * \fBorig_dir\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
