.TH "torture_ssh" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
torture_ssh
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBssh_session\fP \fBsession\fP"
.br
.ti -1c
.RI "void * \fBcb_state\fP"
.br
.ti -1c
.RI "void * \fBcallbacks\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
