.TH "torture_state" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
torture_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBsocket_dir\fP"
.br
.ti -1c
.RI "char * \fBgss_dir\fP"
.br
.ti -1c
.RI "char * \fBpcap_file\fP"
.br
.ti -1c
.RI "char * \fBlog_file\fP"
.br
.ti -1c
.RI "char * \fBsrv_pidfile\fP"
.br
.ti -1c
.RI "char * \fBsrv_config\fP"
.br
.ti -1c
.RI "char * \fBsrv1_pidfile\fP"
.br
.ti -1c
.RI "char * \fBsrv1_config\fP"
.br
.ti -1c
.RI "bool \fBsrv_pam\fP"
.br
.ti -1c
.RI "char * \fBsrv_additional_config\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBssh_session\fP \fBsession\fP"
.br
.ti -1c
.RI "   struct \fBtorture_sftp\fP * \fBtsftp\fP"
.br
.ti -1c
.RI "   struct \fBtorture_ssh\fP \fBssh\fP"
.br
.ti -1c
.RI "} \fBssh\fP"
.br
.ti -1c
.RI "void * \fBprivate_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
