mkdir build
cd build
make clean

cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_STATIC_LIBS=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_TESTING=ON \
    -DBUILD_OSSFUZZ=ON \
    -DENABLE_DEBUG_LOGGING=ON \
    -DCRYPTO_BACKEND=OpenSSL \
    -DENABLE_CRYPT_NONE=ON \
    -DENABLE_MAC_NONE=ON \
    -DLIBSSH2_NO_DEPRECATED=OFF \
    -DCLEAR_MEMORY=ON \
    -DLIBSSH2_USE_PKGCONFIG=ON \
    -DHIDE_SYMBOLS=ON

make
